#!/bin/bash
set -eu

function execute_sql() {
  local cmd
  cmd=${1}
  mysql -N -h ${HOST} -u ${USER} --password=${USER} ${DB_NAME} -e "${cmd}"
}

function drop_all_tables() {
  for table in $(execute_sql 'SHOW TABLES'); do
    echo DROPPING TABLE ${table}
    execute_sql "DROP TABLE ${table}"
  done
}

function main() {
  drop_all_tables
}

main
