#!/bin/bash

set -eu

root_dir="${PWD}"

# Inputs
RUNTIME_CI_DIR="${root_dir}/${RUNTIME_CI_DIR:?"\$RUNTIME_CI_DIR must be provided"}"

function verify_image_exists_in_pipeline_yml {
  set +e
  if ! grep "$(basename "${1}")" "${RUNTIME_CI_DIR}/pipelines/build-docker-images.yml" >/dev/null; then
    echo "${1}"
  fi
  set -e
}

errors_file=$(mktemp /tmp/errors.XXXXX)
pushd "${RUNTIME_CI_DIR}/scripts/ci" >/dev/null
  find . -type d ! -path . -prune | while read -r dir; do
    pushd "${dir}" >/dev/null
      verify_image_exists_in_pipeline_yml "${dir}" >> "${errors_file}"
    popd >/dev/null; done
popd >/dev/null

if [ -s "${errors_file}" ]; then
  echo "The following tasks are missing from the build-docker-image pipeline:"
  cat "${errors_file}"
  exit 1
fi

echo "All tasks have an associated job to build their docker image"
