---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-cli

inputs:
- name: bbl-state
- name: cf-deployment-concourse-tasks
- name: manifest
- name: runtime-ci
- name: pool-lock
  optional: true

outputs:
- name: compiled-release-tarball

run:
  path: runtime-ci/tasks/export-compiled-release-tarball/task

params:
  BBL_STATE_DIR: bbl-state
  DEPLOYMENT_NAME: cf
  RELEASE_NAME:
  MANIFEST_FILENAME: cf-deployment.yml
  STEMCELL_OPS_FILE_PATH:

  BBL_JSON_CONFIG:
  # - Optional
  # - For if you need a dynamic config for BBL
