#!/bin/bash

set -x
set -e
set -u

DIRECTOR_URL=$(bbl --state-dir env-repo/bbl-infrastructure director-address)
DIRECTOR_UUID=$(bosh -t $DIRECTOR_URL status --uuid)

cat <<EOF > manifest/nats.yml
---
name: nats
director_uuid: $DIRECTOR_UUID
networks:
- name: private-override
  type: manual
  subnets:
  - az: z1
    gateway: 10.0.16.1
    range: 10.0.16.0/20
    reserved:
    - 10.0.16.2-10.0.16.3
    - 10.0.31.255
    static:
    - 10.0.16.4
    cloud_properties:
      subnet: subnet-24fdb77c
      security_groups:
      - sg-f624bc8d
  - az: z2
    gateway: 10.0.32.1
    range: 10.0.32.0/20
    reserved:
    - 10.0.32.2-10.0.32.3
    - 10.0.47.255
    static:
    - 10.0.32.4
    cloud_properties:
      subnet: subnet-ffa0e9d5
      security_groups:
      - sg-f624bc8d
  - az: z3
    gateway: 10.0.48.1
    range: 10.0.48.0/20
    reserved:
    - 10.0.48.2-10.0.48.3
    - 10.0.63.255
    static:
    - 10.0.48.4
    cloud_properties:
      subnet: subnet-a995acdf
      security_groups:
      - sg-f624bc8d
releases:
- name: nats
  version: latest
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
instance_groups:
- name: nats-server
  azs: [z1, z2, z3, z4]
  instances: 3
  jobs:
  - name: nats
    release: nats
    properties:
      nats:
        port: 6363
        user: nats
        password: nats
  networks:
  - name: private-override
  vm_type: m3.medium
  stemcell: default
- name: smoke-tests
  azs: [z1]
  vm_type: m3.medium
  stemcell: default
  instances: 1
  lifecycle: errand
  jobs:
  - name: smoke-tests
    release: nats
  networks:
  - name: private-override
EOF
