---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-cli

inputs:
- name: runtime-ci
- name: bbl-state
- name: ops-file
- name: cf-deployment-concourse-tasks

run:
  path: runtime-ci/tasks/bosh-extend-cloud-config/task

params:
  BBL_STATE_DIR: bbl-state
  OPS_FILE_PATH:
