#!/bin/bash -exu

set -o pipefail

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function main() {
  setup_bosh_env_vars

  bosh update-cloud-config -n <(bosh int <(bosh cloud-config) -o ops-file/${OPS_FILE_PATH})
}

main
