#!/bin/sh
set -eux

export GOPATH="${PWD}/gopath"
export PATH="${GOPATH}/bin":${PATH}

cd "${GOPATH}/src/github.com/cloudfoundry-incubator/route-registrar"


go get github.com/onsi/ginkgo/ginkgo

./bin/test
