#!/bin/bash
set -exu

STATE_DIR_PATH=${STATE_DIR_PATH:?"\${STATE_DIR_PATH} is not set"}

#The bbl state.json has some trailing '}' characters causing jq to return a non-zero exit code
set +e
stack_name=$(cat "env-repo/${STATE_DIR_PATH}"  | jq --raw-output .stack.name)
set -e

if [[ -z $stack_name ]]; then
  echo "Unable to retrieve stack name from bbl state file"
  exit 1
fi

logical_physical_mapping=""
for logical_resource_id in $LOGICAL_RESOURCE_IDS; do
  logical_physical_mapping=$(aws cloudformation describe-stack-resource --stack-name "$stack_name" --logical-resource-id "$logical_resource_id" | jq --raw-output .StackResourceDetail.PhysicalResourceId)
  echo "$logical_resource_id $logical_physical_mapping" >> logical-physical-id/"$MAPPING_OUTPUT_FILE"
done
