#!/bin/bash -exu

function setup_bosh_env_vars() {
  set +x
  pushd bbl-state
    BOSH_CA_CERT="$(bbl director-ca-cert)"
    export BOSH_CA_CERT
    BOSH_ENVIRONMENT=$(bbl director-address)
    export BOSH_ENVIRONMENT
    BOSH_CLIENT=$(bbl director-username)
    export BOSH_CLIENT
    BOSH_CLIENT_SECRET=$(bbl director-password)
    export BOSH_CLIENT_SECRET
  popd
  set -x
}

function create_compilation_opsfile() {
  cat << EOF > compilation.yml
---
- type: replace
  path: /name
  value: cf-compilation

- type: replace
  path: /stemcells/alias=default/version
  value: latest

- type: replace
  path: /instance_groups
  value: []

EOF
}

function main() {
  setup_bosh_env_vars
  create_compilation_opsfile
  vars_store="$(mktemp)"

  bosh \
    -n \
    -d cf-dry-run \
    deploy cf-deployment/cf-deployment.yml \
    -o compilation.yml \
}

main

