#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/shared-functions

function update_stemcell_opsfile() {
  local stemcell_version
  stemcell_version=$(cat stemcell/version)

  local stemcell_alias
  stemcell_alias="$(bosh int "ops-files/${ORIGINAL_OPS_FILE_PATH}" --path=/path=~1stemcells~1-/value/alias)"

  update_stemcell_ops_file=$(mktemp)
(
cat << EOF
---
- type: replace
  path: /path=~1stemcells~1-
  value:
    type: replace
    path: /stemcells/-
    value:
      alias: "${stemcell_alias}"
      os: "${STEMCELL_STACK}"
      version: "${stemcell_version}"
EOF
) > "${update_stemcell_ops_file}"

  bosh interpolate "ops-files/${ORIGINAL_OPS_FILE_PATH}" -o "${update_stemcell_ops_file}" > "updated-stemcell-ops-file/${UPDATED_OPS_FILE_PATH}"
}

function generate_commit_message() {
  local current_stemcell_version
  current_stemcell_version="$(bosh interpolate "ops-files/${ORIGINAL_OPS_FILE_PATH}" --path=/path=~1stemcells~1-/value/version)"

  local stemcell_version
  stemcell_version=$(cat stemcell/version)

  if [ "${current_stemcell_version}" == "${stemcell_version}" ]; then
    echo "No stemcell update"
  else
    echo "${STEMCELL_STACK} stemcell updated to ${stemcell_version}"
  fi
}

function main() {
  local root_dir
  root_dir="${1}"

  git clone ops-files updated-stemcell-ops-file

  update_stemcell_opsfile

  generate_commit_message > "${root_dir}/${COMMIT_MESSAGE_PATH}"

  commit_with_message "${root_dir}/updated-stemcell-ops-file" "${root_dir}/${COMMIT_MESSAGE_PATH}"
}

main "${PWD}"
