#!/bin/bash

set -eux

root_dir="${PWD}"

# Inputs
CANARY_APP_ERRAND_MANIFEST="${root_dir}/${CANARY_APP_ERRAND_MANIFEST:?"\$CANARY_APP_ERRAND_MANIFEST not set"}"
RUNTIME_CI_DIR="${root_dir}/${RUNTIME_CI_DIR:?"\$RUNTIME_CI_DIR not set"}"

BOSH_USER="${BOSH_USER:?"\$BOSH_USER not set"}"
BOSH_PASSWORD="${BOSH_PASSWORD:?"\$BOSH_PASSWORD not set"}"
BOSH_DIRECTOR="${BOSH_DIRECTOR:?"\$BOSH_DIRECTOR not set"}"

# The pipeline provides 'BOSH_DIRECTOR' but the bosh_setup script expects
# 'BOSH_TARGET'
export BOSH_TARGET="${BOSH_DIRECTOR}"

"${RUNTIME_CI_DIR}/scripts/ci/bosh_setup"

bosh deployment "${CANARY_APP_ERRAND_MANIFEST}"
bosh run errand push_canary_app --keep-alive

