#!/bin/bash
set -e

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
set +u
source ~/.bashrc
set -u

root_dir="${PWD}"

# Inputs
ENV_DIR="${root_dir}/${ENV_DIR:?"\$ENV_DIR not set"}"

# Outputs
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?"OUTPUT_DIR must be provided"}"

setup_env() {
  export BOSH_LITE_PRIVATE_KEY="${ENV_DIR}/keypair/id_rsa_bosh"

  source "${ENV_DIR}/aws_environment"
  export BOSH_AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
  export BOSH_AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"

  source "${ENV_DIR}/deployments/bosh-lite/boshlite_vagrant_env"
}

provision_bosh_lite() {
  pushd bosh-lite

  BOSH_LITE_INSTANCE_TYPE="m3.2xlarge" vagrant up --provider=aws
  BOSH_LITE_IP="$(vagrant ssh-config 2>/dev/null | grep HostName | awk '{print $2}')"
  echo "${BOSH_LITE_IP}" > "${OUTPUT_DIR}/bosh-lite-ip"

  popd
}

main() {
  setup_env
  provision_bosh_lite
}

main
