#!/bin/bash -eux

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/shared-functions

main() {
  local build_dir="${1}"

  set +x
  load_github_deploy_key "${DEPLOY_KEY}"
  set -x

  local cf_deployment_remote=""
  pushd "${build_dir}/cf-deployment-develop" > /dev/null
    cf_deployment_remote="$(git remote -v | awk '$3 == "(push)" { print $2 }')"
  popd > /dev/null

  if [[ -z "${cf_deployment_remote}" ]]; then
    echo "Failed to determine cf-deployment remote."
    exit 1
  fi

  pushd "${build_dir}/updated-cf-deployment" > /dev/null
    local version
    version=$(cat "${build_dir}/release/version")

    local branch_name
    branch_name="$(branch_name ${RELEASE_NAME} ${version})"

    if branch_exists "." "${branch_name}"; then
      echo "Branch already exists."
      git log "origin/develop...origin/${branch_name}"
    else
      git checkout -B "${branch_name}"
      git remote set-url --push origin "${cf_deployment_remote}"
      git push -u origin "${branch_name}"
    fi
  popd > /dev/null
}

main "${PWD}"
