---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: runtime-ci
- name: cf-deployment-release-candidate
- name: cf-deployment-develop
- name: release

run:
  path: runtime-ci/tasks/push-to-release-branch/task

params:
  DEPLOY_KEY:
  RELEASE_NAME:
