#!/bin/bash -eux

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/shared-functions

main() {
  local build_dir="${1}"

  set +x
  local deploy_key_location
  deploy_key_location="$(mktemp)"

  echo "${DEPLOY_KEY}" > "${deploy_key_location}"
  chmod 0600 "${deploy_key_location}"
  eval "$(ssh-agent -s)"
  ssh-add "${deploy_key_location}"
  rm "${deploy_key_location}"

  mkdir -p "${HOME}/.ssh"
  ssh-keyscan github.com,192.30.255.113 github.com,192.30.255.112 >> "${HOME}/.ssh/known_hosts"
  set -x

  local cf_deployment_remote=""
  pushd "${build_dir}/cf-deployment-develop" > /dev/null
    cf_deployment_remote="$(git remote -v | awk '$3 == "(push)" { print $2 }')"
  popd > /dev/null

  if [[ -z "${cf_deployment_remote}" ]]; then
    echo "Failed to determine cf-deployment remote."
    exit 1
  fi

  pushd "${build_dir}/cf-deployment-release-candidate" > /dev/null
    local version
    version=$(cat "${build_dir}/release/version")

    local branch_name
    branch_name="update-${RELEASE_NAME}-release-${version}"

    if branch_exists "." "${branch_name}"; then
      echo "Branch already exists."
      git log "origin/develop...origin/${branch_name}"
    else
      git checkout -B "${branch_name}"
      git remote set-url --push origin "${cf_deployment_remote}"
      git push -u origin "${branch_name}"
    fi
  popd > /dev/null
}

main "${PWD}"
