#!/bin/bash

set -uex

root_dir="${PWD}"
INFRASTRUCTURE="${INFRASTRUCTURE:?"\$INFRASTRUCTURE not set"}"
IAAS_SETTINGS_TEMPLATE_PATH="${root_dir}/deployments/${IAAS_SETTINGS_TEMPLATE_PATH:?"\$IAAS_SETTINGS_TEMPLATE_PATH not set"}"
IAAS_SETTINGS_STUB_PATH="${root_dir}/deployments/${IAAS_SETTINGS_STUB_PATH:?"\$IAAS_SETTINGS_STUB_PATH not set"}"

output_dir="${root_dir}/iaas-settings"

pushd diego-release > /dev/null
  spiff merge \
    "manifest-generation/misc-templates/${INFRASTRUCTURE}-iaas-settings.yml" \
    "${IAAS_SETTINGS_TEMPLATE_PATH}" \
    "${IAAS_SETTINGS_STUB_PATH}" \
    > "${output_dir}/iaas-settings.yml"
popd > /dev/null

