---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: latest

inputs:
- name: runtime-ci # - This repo
- name: cf-deployment
- name: stemcell

outputs:
  - name: stemcell-bump-type

run:
  path: runtime-ci/tasks/detect-stemcell-bump/task
