#!/bin/bash -exu

function main() {
  local root_dir
  root_dir="${1}"

  export GOPATH="${root_dir}/go"
  export PATH=$GOPATH/bin:$PATH

  ln -s release "${RELEASE_NAME}-release"

  ln -s compiled-release-tarball "${RELEASE_NAME}-compiled-release-tarball"

  cp -r original-compiled-release-ops-file/* updated-compiled-release-ops-file

  if [ -f current-commit-message/"${COMMIT_MESSAGE_PATH}" ]; then
    cp current-commit-message/"${COMMIT_MESSAGE_PATH}" commit-message/"${COMMIT_MESSAGE_PATH}"
  fi

  pushd "${GOPATH}/src/github.com/cloudfoundry/runtime-ci/util/update-manifest-releases"
    go run main.go --build-dir "${root_dir}" --release "${RELEASE_NAME}" --target "compiledReleasesOpsfile"
  popd
}

main "${PWD}"
