---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: runtime-ci
  path: go/src/github.com/cloudfoundry/runtime-ci
- name: original-compiled-releases-ops-file
- name: release
- name: compiled-release-tarball

outputs:
- name: updated-compiled-releases-ops-file

run:
  path: go/src/github.com/cloudfoundry/runtime-ci/tasks/update-single-compiled-release/task

params:
  RELEASE_NAME:
  ORIGINAL_OPS_FILE_PATH:
  UPDATED_OPS_FILE_PATH:
