#!/bin/bash -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function setup_interpolate_env_vars_for_first_ops_file() {
  local ops_to_test
  set +e
  ops_to_test=$(find modified-ops-files -name '*.yml' -not -path '*/community/*' | cut -d'/' -f 2- |  head -1 | xargs find ops-files -type f -not -path '*/community/*' -name | cut -d'/' -f 2-)
  set -e

  export MANIFEST_FILE=cf-deployment.yml

  if [[ "${PREPEND_OPS_FILE_TO_LIST}" == "true" ]]; then
    OPS_FILES="$ops_to_test $OPS_FILES"
  else
    OPS_FILES="$OPS_FILES $ops_to_test"
  fi
}

function main() {
  load_from_json_config

  check_input_params
  setup_bosh_env_vars
  setup_interpolate_env_vars_for_first_ops_file
  bosh_interpolate
  if [ "$REGENERATE_CREDENTIALS" == true ]; then
    remove_credentials_from_credhub
  fi
  upload_stemcells
  # shellcheck disable=SC2086
  bosh_deploy ${BOSH_DEPLOY_ARGS}
}

main
