---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: bbl-state
- name: cf-deployment
- name: ops-files
- name: modified-ops-files
- name: vars-files
- name: runtime-ci
- name: cf-deployment-concourse-tasks
- name: pool-lock
  optional: true

run:
  path: runtime-ci/tasks/bosh-deploy-with-first-ops/task

params:
  BBL_STATE_DIR: bbl-state
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to the `bbl-state` input
  # - If blank or '.', uses `bbl-state` input as the location for bbl state
  # - If the specified path does not exist, it will be created

  MANIFEST_FILE: cf-deployment.yml
  # - Required
  # - Filepath to the manifest file within the cf-deployment resource
  # - The path is relative to root of the `cf-deployment` input

  SYSTEM_DOMAIN:
  # - Required
  # - CF system base domain e.g. `my-cf.com`

  OPS_FILES:
  # - Optional
  # - List of operations files to be applied to the manifest
  # - Quoted and space-separated
  # - Ops will be applied in the order they're listed
  # - Paths are relative to root of the `ops-files` input

  VARS_FILES:
  # - Optional
  # - List of variable files to be applied to the manifest
  # - Quoted and space-separated
  # - Variable files will be applied in the order they're listed
  # - Paths are relative to root of the `vars-files` input

  REGENERATE_CREDENTIALS: false
  # - Optional
  # - Delete credentials associated with this deployment from CredHub
  # - This allows the credentials to be freshly generated each time
  # - This is helpful for testing changes around variable generation
  # - Works well with fresh deployments
  # - Upgrade deployments are not expected to work with total cred rotation

  # Uptimer Params
  # https://github.com/cloudfoundry/uptimer
  DEPLOY_WITH_UPTIME_MEASUREMENTS: false
  # - Optional
  # - This will measure uptime during the bosh deploy task.

  MEASURE_SYSLOG_AVAILABILITY: false
  # - Optional
  # - Requires DEPLOY_WITH_UPTIME_MEASUREMENTS to be true.
  # - This will measure availability of app syslog drain during deployment.

  TCP_DOMAIN:
  # - Required if MEASURE_SYSLOG_AVAILABILITY is set to true.
  # - Domain in which to create a tcp route for the syslog availability measurement.

  AVAILABLE_PORT:
  # - Required if MEASURE_SYSLOG_AVAILABILITY is set to true.
  # - Available port within the 'reservable_ports' range,
  # - used to create a tcp route for the syslog availability measurement.

  FAIL_ON_DOWNTIME: false
  # - Optional
  # - This will cause the task to fail if you are not using the DEPLOY_WITH_UPTIME_MEASUREMENTS flag
  # - It will cause the concourse task to fail if you do not have perfect uptime

  APP_PUSHABILITY_THRESHOLD: 0
  # - Optional
  # - This sets the maximum number of allowed uptimer failures for app pushability
  # - The default threshold value of 0 is our working value for cf-deployment, and is likely to be updated

  HTTP_AVAILABILITY_THRESHOLD: 0
  # - Optional
  # - This sets the maximum number of allowed uptimer failures for http availability
  # - The default threshold value of 0 is our working value for cf-deployment, and is likely to be updated

  RECENT_LOGS_THRESHOLD: 0
  # - Optional
  # - This sets the maximum number of allowed uptimer failures for recent logs
  # - The default threshold value of 0 is our working value for cf-deployment, and is likely to be updated

  STREAMING_LOGS_THRESHOLD: 0
  # - Optional
  # - This sets the maximum number of allowed uptimer failures for streaming logs
  # - The default threshold value of 0 is our working value for cf-deployment, and is likely to be updated

  APP_SYSLOG_AVAILABILITY_THRESHOLD: 0
  # - Optional
  # - This sets the maximum number of allowed uptimer failures for app syslog availability
  # - The default threshold value of 0 is our working value for cf-deployment, and is likely to be updated

  USE_SINGLE_APP_INSTANCE: false
  # - Optional
  # - Configures uptimer to deploy with a single app instance rather than two.
  # - This is primarily used by Diego to validate new uptime features.

  BOSH_DEPLOY_ARGS:
  # - Optional
  # - Supplies additional arguments to the bosh deploy command
  # - For example, '--recreate'

  BOSH_LITE: false
  # - Optional
  # - Used to determine whether we should upload a warden stemcell
  # - Boolean

  BBL_JSON_CONFIG:
  # - Optional
  # - For if you need a dynamic config for BBL

  PREPEND_OPS_FILE_TO_LIST: false
  # - Optional
  # - Prepend the ops files to the beginning of the provided list, rather than appending to the end
