#!/bin/bash
set -exu

STATE_DIR_PATH=${STATE_DIR_PATH:?"\${STATE_DIR_PATH} is not set"}

#The bbl state.json has some trailing '}' characters causing jq to return a non-zero exit code
set +e
stack_name=$(cat "env-repo/${STATE_DIR_PATH}"  | jq --raw-output .stack.name)
set -e

if [[ -z $stack_name ]]; then
  echo "Unable to retrieve stack name from bbl state file"
  exit 1
fi

internal_security_group=$(aws cloudformation describe-stack-resource --stack-name "$stack_name" --logical-resource-id InternalSecurityGroup | jq --raw-output .StackResourceDetail.PhysicalResourceId)
cf_router_internal_security_group=$(aws cloudformation describe-stack-resource --stack-name "$stack_name" --logical-resource-id CFRouterInternalSecurityGroup | jq --raw-output .StackResourceDetail.PhysicalResourceId)

cat <<EOF >./security-groups/security-groups
INTERNAL_SECURITY_GROUP $internal_security_group
CF_ROUTER_INTERNAL_SECURITY_GROUP $cf_router_internal_security_group
EOF
