version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/ci/resources/stemcell-version-bump"
  - "/tasks/lookup-slack-channel-for-release-owner"
  - "/util/cat-search-tool"
  - "/util/update-manifest-releases"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directories:
  - "/dockerfiles/bosh-cli"
  - "/dockerfiles/relint-base"
  schedule:
    interval: "weekly"
