version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "gomod"
  directory: "/ci/resources/stemcell-version-bump"
  schedule:
    interval: "weekly"

- package-ecosystem: "gomod"
  directory: "/tasks/lookup-slack-channel-for-release-owner"
  schedule:
    interval: "weekly"

- package-ecosystem: "gomod"
  directory: "/util/cat-search-tool"
  schedule:
    interval: "weekly"

- package-ecosystem: "gomod"
  directory: "/util/update-manifest-releases"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directory: "/dockerfiles/bosh-cli"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directory: "/dockerfiles/relint-base"
  schedule:
    interval: "weekly"
