#!/bin/bash
set -xeu

export CONFIG
CONFIG="$PWD/integration-config/${CONFIG_FILE_PATH}"

echo "Moving cf-routing-acceptance-tests onto the gopath..."
mkdir -p $GOPATH
cp -R routing-release/src $GOPATH

go install github.com/onsi/ginkgo/ginkgo

cd ${GOPATH}/src/code.cloudfoundry.org/routing-acceptance-tests

ginkgo -r smoke_tests/ \
  -slowSpecThreshold=120 \
  -keepGoing \
  -randomizeAllSpecs \
  -skipPackage=helpers \
  -slowSpecThreshold=120 \
  -nodes="${NODES}"
