#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

pushd $CF_RELEASE_DIR
  git branch -D develop_release_test
  git checkout develop_release_test
  git merge --no-ff origin/master_release_test
popd




