#!/bin/bash
set -exu

SCRIPT_DIR=runtime-ci/tasks/cf-deployment-release-notes-template

pushd $SCRIPT_DIR
  bundle config set --local without development
  bundle install
popd

BUNDLE_GEMFILE=$SCRIPT_DIR/Gemfile \
  bundle exec ruby $SCRIPT_DIR/task.rb
