#!/bin/bash
set -exu

root_dir="${PWD}"

# Inputs
BOSH_TARGET=$(cat "${BOSH_TARGET_FILE:?"Path to BOSH_TARGET_FILE must be provided"}")
BOSH_USER=$(cat "${BOSH_USER_FILE:?"Path to BOSH_USER_FILE must be provided"}")
ERRAND_NAME="${ERRAND_NAME:?"ERRAND_NAME must be provided"}"
DEPLOYMENT_NAME="${DEPLOYMENT_NAME:?"DEPLOYMENT_NAME must be provided"}"

set +x
BOSH_PASSWORD=$(cat "${BOSH_PASSWORD_FILE:?"Path to BOSH_PASSWORD_FILE must be provided"}")
set -x

# Outputs
LOGS_DIR="${root_dir}/${LOGS_DIR}"

set +x
echo 'bosh \
  -t "${BOSH_TARGET}" \
  -u "${BOSH_USER}" \
  -p "REDACTED" \
  download manifest \
  "$DEPLOYMENT_NAME" \
  manifest.yml'

bosh \
  -t "${BOSH_TARGET}" \
  -u "${BOSH_USER}" \
  -p "${BOSH_PASSWORD}" \
  download manifest \
  "$DEPLOYMENT_NAME" \
  manifest.yml

echo 'bosh \
  -n \
  --color \
  -t "$BOSH_TARGET" \
  -u "${BOSH_USER}" \
  -p "REDACTED" \
  -d manifest.yml \
  run errand "$ERRAND_NAME" \
  --keep-alive \
  --download-logs \
  --logs-dir "$LOGS_DIR"'

bosh \
  -n \
  --color \
  -t "${BOSH_TARGET}" \
  -u "${BOSH_USER}" \
  -p "${BOSH_PASSWORD}" \
  -d manifest.yml \
  run errand "$ERRAND_NAME" \
  --keep-alive \
  --download-logs \
  --logs-dir "$LOGS_DIR"
set -x
