#!/bin/bash
set -exu

root_dir="${PWD}"

# Inputs
BOSH_DIRECTOR=$(cat ${TARGET_FILE:?"Path to TARGET_FILE must be provided"})
BOSH_USER=$(cat ${USERNAME_FILE:?"Path to USERNAME_FILE must be provided"})
ERRAND_NAME="${ERRAND_NAME:?"ERRAND_NAME must be provided"}"
DEPLOYMENT_NAME="${DEPLOYMENT_NAME:?"DEPLOYMENT_NAME must be provided"}"

set +x
BOSH_PASSWORD=$(cat ${PASSWORD_FILE:?"Path to PASSWORD_FILE must be provided"})
set -x

# Outputs
LOGS_DIR="${root_dir}/${LOGS_DIR}"

bosh -t "$BOSH_DIRECTOR" download manifest "$DEPLOYMENT_NAME" manifest.yml

bosh \
  -n \
  --color \
  -t "$BOSH_DIRECTOR" \
  -d manifest.yml \
  run errand "$ERRAND_NAME" \
  --keep-alive \
  --download-logs \
  --logs-dir "$LOGS_DIR"
