#!/bin/bash
set -eux

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function upload_stemcell() {
  bosh \
    -n \
    upload-stemcell \
    stemcell/${STEMCELL_NAME}
}

function main() {
  setup_bosh_env_vars
  upload_stemcell
}

main
