---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: bbl-state
- name: runtime-ci
- name: stemcell
- name: cf-deployment-concourse-tasks

run:
  path: runtime-ci/tasks/bosh-upload-stemcell/task

params:
  BBL_STATE_DIR:
