---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: latest

inputs:
- name: runtime-ci
- name: cf-deployment

run:
  path: runtime-ci/tasks/summarize-ops-files/task

params:
  TASK_LIST: "bosh-deploy-cf-latest-release bosh-deploy-cf-develop"
