#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/cf-deployment-concourse-tasks/shared-functions

trap close_bbl_ssh_connection EXIT

function validate_variables() {
  BOSH_RELEASE="${BOSH_RELEASE:?"BOSH_RELEASE must be provided"}"
  STEMCELL_OS="${STEMCELL_OS:?"STEMCELL_OS must be provided"}"
  DEPLOYMENT_NAME="${DEPLOYMENT_NAME:?"DEPLOYMENT_NAME must be provided"}"
}

function export_release() {
  local stemcell_os_version
  stemcell_os_version=$(bosh interpolate cf-deployment/cf-deployment.yml --path "/stemcells/os=${STEMCELL_OS}/version")
  local bosh_release_version
  bosh_release_version=$(bosh interpolate cf-deployment/cf-deployment.yml --path "/releases/name=${BOSH_RELEASE}/version")
  pushd exported-release
    bosh export-release -d "${DEPLOYMENT_NAME}" "${BOSH_RELEASE}/${bosh_release_version}" "${STEMCELL_OS}/${stemcell_os_version}"
  popd
}

function main() {
  setup_bosh_env_vars
  validate_variables
  export_release
}

main
