#!/bin/bash
set -exu

BOSH_LITE_IP="${BOSH_LITE_IP:?"\$BOSH_LITE_IP not set"}"

create_stub() {
  bosh -t "${BOSH_LITE_IP}" login admin admin
  DIRECTOR_UUID=$(bosh -t "${BOSH_LITE_IP}" status --uuid)
  cat << EOF > bosh-lite-stub/stub.yml
director_uuid: $DIRECTOR_UUID
properties:
  acceptance_tests:
    nodes: 4
    include_backend_compatibility: true
    include_diego_docker: true
    include_diego_ssh: true
    include_internet_dependent: true
    include_logging: true
    include_operator: true
    include_route_services: true
    include_security_groups: true
    include_services: true
    include_sso: true
    include_v3: true
    include_tasks: true
    backend: diego
  cc:
    default_to_diego_backend: true
    security_group_definitions:
      - name: load_balancer
        rules:
        - protocol: all
          destination: ${BOSH_LITE_IP}

EOF

  cat bosh-lite-stub/stub.yml
}

main() {
  create_stub
}

main
