#!/bin/bash
set -exu

BOSH_LITE_IP="${BOSH_LITE_IP:?"\$BOSH_LITE_IP not set"}"

create_stub() {
  ruby -ryaml -e "puts ({
    'director_uuid' => 'f314cc48-5260-4d52-968d-bcec8f8eff0f',
    'properties' => {
      'login' => {
        'saml' => {
          'serviceProviderKey' => ENV['SAML_SERVICE_PROVIDER_KEY'],
          'serviceProviderKeyPassword' => '',
          'serviceProviderCertificate' => ENV['SAML_SERVICE_PROVIDER_CERTIFICATE']
        }
      },
      'system_domain' => 'bosh-lite.runtime-ci.cf-app.com',
      'apps_domain' => 'bosh-lite.runtime-ci.cf-app.com',
      'acceptance_tests' => {
        'nodes' => 8,
        'api' => 'api.bosh-lite.runtime-ci.cf-app.com',
        'apps_domain' => 'bosh-lite.runtime-ci.cf-app.com',
        'include_sso' => true,
        'include_security_groups' => true,
        'include_internet_dependent' => true,
        'include_services' => true,
        'include_v3' => false,
        'include_route_services' => true,
        'include_diego_docker' => true,
        'include_diego_ssh' => true,
        'include_backend_compatibility' => false,
        'include_tasks' => true,
        'include_persistent_app' => false,
        'include_privileged_container_support' => true,
        'include_zipkin' => false,
        'cf_dial_timeout_in_seconds' => 6,
        'use_http' => true,
        'skip_ssl_validation' => true,
      },
      'cc' => {
        'security_group_definitions' => [
          'name' => 'load_balancer',
          'rules' => [
            'protocol' => 'all',
            'destination' => ENV['BOSH_LITE_IP'],
          ]
        ]
      }
    }
  }).to_yaml" > bosh-lite-stub/stub.yml
}

main() {
  create_stub
}

main
