#!/bin/bash

set -exu

export DIRECTOR_UUID=$(bosh interpolate --path=/director_uuid "${CF_MANIFEST_PATH}" | head)

routing-release/scripts/generate-manifest \
-c "${CF_MANIFEST_PATH}" \
-d "${DIEGO_MANIFEST_PATH}" \
-l "${IAAS_SETTINGS_PATH}" \
-l "${PROPERTY_OVERRIDES_PATH}" \
-l "${INSTANCE_COUNT_OVERRIDES_PATH}" \
-l "${PERSISTENT_DISK_OVERRIDES_PATH}" \
> routing-manifest/routing-deployment.yml
