#!/bin/bash
set -exu

root_dir="${PWD}"

# Inputs
RELEASE_REPO_DIR="${root_dir}/${RELEASE_REPO_DIR:?"\$RELEASE_REPO_DIR not set"}"
RELEASE_REPO_MASTER_DIR="${root_dir}/${RELEASE_REPO_MASTER_DIR:?"\$RELEASE_REPO_MASTER_DIR not set"}"
CF_RELEASE_DIR="${root_dir}/${CF_RELEASE_DIR:?"\$CF_RELEASE_DIR not set"}"
CONSUL_RELEASE_DIR="${root_dir}/${CONSUL_RELEASE_DIR:?"\$CONSUL_RELEASE_DIR not set"}"
ETCD_RELEASE_DIR="${root_dir}/${ETCD_RELEASE_DIR:?"\$ETCD_RELEASE_DIR not set"}"
STEMCELL_DIR="${root_dir}/${STEMCELL_DIR:?"\$STEMCELL_DIR not set"}"

# Outputs
BLESSED_REPO_DIR="${root_dir}/${BLESSED_REPO_DIR:?"\$BLESSED_REPO_DIR not set"}"

pushd "${RELEASE_REPO_DIR}"
  git config user.name "CF MEGA BOT"
  git config user.email "cf-mega@pivotal.io"

  git remote add -f master-repo "${RELEASE_REPO_MASTER_DIR}"
  git merge "master-repo/master" -m 'Merge with master'

  git status
  git show --color | cat

  ./scripts/generate_blessed_versions \
      "${STEMCELL_DIR}/"*.tgz \
      "${CF_RELEASE_DIR}" \
      "${ETCD_RELEASE_DIR}/"*.tgz \
      "${CONSUL_RELEASE_DIR}/"*.tgz

  git status
  git show --color | cat
popd

cp -r "${RELEASE_REPO_DIR}" "${BLESSED_REPO_DIR}/release-repo"
