#!/bin/bash
set -eux

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/shared-functions

get_git_sha() {
  local repo
  repo=${1}
  pushd ${repo} > /dev/null
    git rev-parse HEAD
  popd > /dev/null
}

get_git_tag() {
  local repo
  repo=${1}
  pushd ${repo} > /dev/null
    git describe --tags
  popd > /dev/null
}

clone_git_repo() {
  local destination
  destination=${1}
  set +x
  deploy_key_location=$(mktemp)
  echo "${DEPLOY_KEY}" > ${deploy_key_location}
  chmod 0600 ${deploy_key_location}
  eval "$(ssh-agent -s)"
  ssh-add ${deploy_key_location}
  rm ${deploy_key_location}
  mkdir -p ${HOME}/.ssh
  ssh-keyscan github.com,192.30.255.113 github.com,192.30.255.112 >> ${HOME}/.ssh/known_hosts
  set -x
  git clone git@github.com:cloudfoundry/cf-acceptance-tests.git ${destination}
}

main() {
  build_dir=$PWD
  local cf_deployment_tag
  cf_deployment_tag=$(get_git_tag cf-deployment)

  local cats_branch_name
  cats_branch_name=$(echo ${cf_deployment_tag} | sed -e 's/^v\([[:digit:]]\+\.[[:digit:]]\+\)\..*/cf\1/')

  local cf_acceptance_tests_sha
  cf_acceptance_tests_sha=$(get_git_sha cf-acceptance-tests)

  # cats_to_branch=$(mktemp -d)
  cats_to_branch=${build_dir}/branched-cats
  clone_git_repo ${cats_to_branch}
  pushd ${cats_to_branch} > /dev/null
    if $(branch_exists . ${cats_branch_name}) ; then
      git checkout ${cats_branch_name}
    else
      git checkout ${cf_acceptance_tests_sha}
      git checkout -b ${cats_branch_name}
      git push -u origin ${cats_branch_name}
    fi
    git remote add master-cats ${build_dir}/cf-acceptance-tests
    git remote update
    git merge --ff-only master-cats/master
    git push
  popd > /dev/null
}

main
