#!/bin/bash
set -exu

function check_input_params() {
  if [ -z "$DEPLOYMENT_NAME" ]; then
    echo "DEPLOYMENT_NAME has not been set"
    exit 1
  fi
  if [ -z "$ERRAND_NAME" ]; then
    echo "ERRAND_NAME has not been set"
    exit 1
  fi
}

function setup_bosh_env_vars() {
  set +x
  pushd "bbl-state/${BBL_STATE_DIR}"
    BOSH_CA_CERT="$(bbl director-ca-cert)" && export BOSH_CA_CERT
    BOSH_ENVIRONMENT="$(bbl director-address)" && export BOSH_ENVIRONMENT
    BOSH_CLIENT="$(bbl director-username)" && export BOSH_CLIENT
    BOSH_CLIENT_SECRET="$(bbl director-pasword)" && export BOSH_CLIENT_SECRET
  popd
  set -x
}

function bosh_run_errand() {
  bosh run-errand -d "${DEPLOYMENT_NAME}" "${ERRAND_NAME}"
}

function main() {
  check_input_params
  setup_bosh_env_vars
  bosh_run_errand
}

main
