#!/bin/bash

set -exu

git clone cf-deployment-transition-compatibility updated-cf-deployment-transition-compatibility
pushd cf-deployment-release-candidate
  git_sha=$(git rev-parse release-candidate)
popd
cf_deployment_version="v$(cat cf-deployment-version/version)"

existing_row_for_version=$(awk -F"," "BEGIN {OFS=\",\"} \$10 == \"${cf_deployment_version}\" { print \$0 }" cf-deployment-transition-compatibility/transition-compatibility.csv)
if [ -n "${existing_row_for_version}" ];then
  echo "[ERROR] There is already a row in this cf-deployment-transition-compatibility matrix for version ${cf_deployment_version}; aborting"
  exit 1
fi

updated_row=$(awk -F"," "BEGIN {OFS=\",\"} \$5 == \"${git_sha}\" { \$5=\"\"; \$10=\"${cf_deployment_version}\"; print \$0 }" cf-deployment-transition-compatibility/transition-compatibility.csv)
if [ -z "${updated_row}" ]; then
  echo "[WARN] Unable to find match in cf-deployment-transition-compatibility table for sha ${git_sha}.  Skipping update."
  exit 0
fi

cd updated-cf-deployment-transition-compatibility
echo ${updated_row} >> transition-compatibility.csv
git add transition-compatibility.csv
git config user.email "cf-release-integration@pivotal.io"
git config user.name  "CI (automated)"
git commit -m "Add row to compatibility matrix for cfd sha ${git_sha} and cfd version ${cf_deployment_version}"
