#!/bin/bash -eux

function branch_exists() {
  local repo
  repo="${1}"

  local branch_name
  branch_name="${2}"

  pushd "${repo}" > /dev/null
    if [[ -n "$(git branch -r --list "origin/${branch_name}")" ]]; then
      return 0
    else
      return 1
    fi
  popd > /dev/null
}

function commit_with_message() {
  local repo_dir="${1}"
  local commit_message_file="${2}"

  pushd "${repo_dir}" > /dev/null
    if [[ -z "$(git status --porcelain)" ]]; then
      return
    fi

    git config user.name "CF RELINT BOT"
    git config user.email "cf-release-integration@pivotal.io"

    git add .

    local commit_message
    commit_message="$(cat "${commit_message_file}")"

    if [[ -z "${commit_message}" ]]; then
      commit_message="No changes"
    fi

    git commit -m "${commit_message}"

    git status
    git show --color | cat
  popd > /dev/null
}

function branch_name() {
  echo "update-$1-release-$2"
}
