#!/bin/bash -exu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function move_cf_admin_password() {
  setup_password_from_credhub "cf_admin_password"
  bosh_director_name=$(jq -r .bosh.directorName bbl-state/${BBL_STATE_DIR}/bbl-state.json)

  set +x
    credhub s -n /${bosh_director_name}/cf-smoke-tests/cf_admin_password -t password -w ${cf_admin_password}
  set -x
}

function bosh_deploy() {
  bosh create-release --dir cf-smoke-tests-release --tarball smokes.tgz --timestamp-version
  bosh upload-release --dir cf-smoke-tests-release ./smokes.tgz

  local root_dir=$PWD
  cat << EOF > smokes-dev-release.yml
---
name: cf-smoke-tests
update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 5
  serial: false
  update_watch_time: 5000-1200000
addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-xenial
  jobs:
  - name: bpm
    release: bpm
instance_groups:
- name: smoke-tests
  lifecycle: errand
  azs:
  - z1
  instances: 1
  vm_type: small
  stemcell: default
  update:
    max_in_flight: 1
    serial: true
  networks:
  - name: default
  jobs:
  - name: cf-cli-6-linux
    release: cf-cli
  - name: smoke_tests
    release: cf-smoke-tests
    properties:
      smoke_tests:
        api: "https://api.((system_domain))"
        apps_domain: "((system_domain))"
        user: admin
        password: "((cf_admin_password))"
        org: cf_smoke_tests_org
        space: cf_smoke_tests_space
        cf_dial_timeout_in_seconds: 300
        skip_ssl_validation: true

- name: smoke-tests-windows
  lifecycle: errand
  azs:
  - z1
  instances: 1
  vm_type: small
  vm_extensions:
  - 100GB_ephemeral_disk
  stemcell: windows2016
  update:
    max_in_flight: 1
    serial: true
  networks:
  - name: default
  jobs:
  - name: smoke_tests_windows
    release: cf-smoke-tests
    properties:
      smoke_tests:
        api: "https://api.((system_domain))"
        apps_domain: "((system_domain))"
        user: admin
        password: "((cf_admin_password))"
        org: cf_smoke_tests_org
        space: cf_smoke_tests_space
        cf_dial_timeout_in_seconds: 300
        skip_ssl_validation: true

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
- alias: windows2016
  os: windows2016
  version: latest

releases:
- name: cf-smoke-tests
  version: latest
- name: cf-cli
  version: latest
- name: bpm
  version: latest
EOF

  bosh \
    -n \
    -d "${RELEASE_NAME}" \
    interpolate smokes-dev-release.yml \
    -v system_domain="${SYSTEM_DOMAIN}" > interpolated-manifest.yml

  bosh \
    -n \
    deploy \
    -d "${RELEASE_NAME}" \
    interpolated-manifest.yml
}

function main() {
  setup_bosh_env_vars
  move_cf_admin_password
  bosh_deploy
}

main
