---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: bbl-state
- name: cf-smoke-tests-release
- name: runtime-ci
- name: cf-deployment-concourse-tasks

run:
  path: runtime-ci/tasks/bosh-deploy-smokes/task

params:
  BBL_STATE_DIR: bbl-state
  RELEASE_NAME: cf-smoke-tests
  SYSTEM_DOMAIN:
  CREDHUB_ENV_NAME:
