#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

if [ -n "$LOGS_DIR" ]; then
  mkdir $LOGS_DIR
fi

bosh -n --color -t $BOSH_DIRECTOR cleanup
