#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc
set -u

# Inputs
BOSH_DIRECTOR="${BOSH_DIRECTOR:?"BOSH_DIRECTOR must be provided"}"
BOSH_USER="${BOSH_USER:?"BOSH_USER must be provided"}"

set +x
BOSH_PASSWORD="${BOSH_PASSWORD:?"BOSH_PASSWORD must be provided"}"
set -x

bosh -n --color -t "${BOSH_DIRECTOR}" cleanup
