#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/cf-deployment-concourse-tasks/shared-functions

function create_latest_stemcell_opsfile() {
  cat << EOF > latest_stemcell.yml
---
- type: replace
  path: /name
  value: cf-dry-run${DEPLOYMENT_NAME_SUFFIX}

- type: replace
  path: /stemcells/alias=default/version
  value: latest
EOF
}

function main() {
  setup_bosh_env_vars
  create_latest_stemcell_opsfile
  vars_store="$(mktemp)"

  bosh \
    -n \
    -d cf-dry-run${DEPLOYMENT_NAME_SUFFIX} \
    interpolate cf-deployment/cf-deployment.yml \
    --vars-store "${vars_store}" \
    --var-errs \
    --var-errs-unused \
    -v system_domain="greengrass.cf-app.com" \
    -o latest_stemcell.yml \
    -o ops-files/operations/gcp.yml > /dev/null

  bosh \
    -n \
    -d cf-dry-run${DEPLOYMENT_NAME_SUFFIX} \
    deploy cf-deployment/cf-deployment.yml \
    --dry-run \
    --vars-store="${vars_store}" \
    -v system_domain="greengrass.cf-app.com" \
    -o latest_stemcell.yml \
    -o ops-files/operations/gcp.yml
}

main
