#!/bin/bash
set -exu

# Inputs
BOSH_DIRECTOR="${BOSH_DIRECTOR:?"BOSH_DIRECTOR must be provided"}"
BOSH_USER="${BOSH_USER:?"BOSH_USER must be provided"}"

set +x
BOSH_PASSWORD="${BOSH_PASSWORD:?"BOSH_PASSWORD must be provided"}"
set -x

bosh -n --color -t "${BOSH_DIRECTOR}" cleanup
