#!/bin/bash
set -exu

# Inputs
BOSH_TARGET=$(cat "target/${TARGET_FILE_PATH}")
export BOSH_USER=$(cat username/"${USERNAME_FILE_PATH}")
set +x
export BOSH_PASSWORD=$(cat "password/${PASSWORD_FILE_PATH}")
set -x

bosh -n --color -t "${BOSH_TARGET}" cleanup --all
