---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: bbl-state
- name: runtime-ci
- name: cf-deployment-concourse-tasks
- name: cf-deployment
- name: stemcell

run:
  path: runtime-ci/tasks/deploy-all-releases/task

params:
  BBL_STATE_DIR:
