#!/bin/bash -eu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function main() {
  local cwd="${PWD}"

  setup_bosh_env_vars

  pushd runtime-ci/tasks/deploy-all-releases
    go run main.go $cwd
  popd
}

main
