#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export MY_DIR

root_dir="${MY_DIR}/../../../"

pushd "${root_dir}" > /dev/null
  bundle install
  bundle exec rspec \
    --color \
    "${MY_DIR}/validate_jobs_public.rb"
popd > /dev/null
