#!/bin/bash
set -exu

# Inputs
RUNTIME_CI_DIR="${PWD}/${RUNTIME_CI_DIR:?"\$RUNTIME_CI_DIR not set"}"

pushd "${RUNTIME_CI_DIR}" > /dev/null
  bundle install
  bundle exec rspec \
    --color \
    "scripts/ci/validate-all-jobs-public/validate_jobs_public.rb"
popd > /dev/null
