---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: runtime-ci
- name: cf-deployment-concourse-tasks
- name: bbl-state

outputs:
- name: bosh-logs

run:
  path: runtime-ci/tasks/retrieve-bosh-logs/task

params:
  BBL_STATE_DIR: bbl-state
  DEPLOYMENT_NAME: cf
