#!/bin/bash -exu
parse_labels() {
  local labels
  labels=""
  for label in ${TRACKER_STORY_LABELS}
  do
    if [ -z "${labels}" ]; then
      labels="\"${label}\""
    else
      labels="${labels}, \"${label}\""
    fi
  done

  echo "${labels}"
}

create_tracker_request_body() {
  if [[ -d tracker-story-post-body ]]; then
    cat tracker-story-post-body/body.json
  else
    cat << EOF
{
  "name": "${TRACKER_STORY_NAME_PREFIX} ${TRACKER_STORY_NAME}",
  "story_type": "${TRACKER_STORY_TYPE}",
  "current_state": "${TRACKER_STORY_STATE}",
  "estimate": ${TRACKER_STORY_ESTIMATE},
  "labels": [${labels}]
}
EOF
  fi
}

set +x


main() {
  local labels
  labels=$(parse_labels)

  echo "$(create_tracker_request_body)"
  curl -f \
    -H "X-TrackerToken: ${TRACKER_API_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "$(create_tracker_request_body)" \
    "https://www.pivotaltracker.com/services/v5/projects/${TRACKER_PROJECT_ID}/stories"
}

main
