#!/bin/bash -exu

create_tracker_request_body() {
  cat << EOF
{
  "name": "${TRACKER_STORY_NAME_PREFIX} ${TRACKER_STORY_NAME}",
  "story_type": "${TRACKER_STORY_TYPE}",
  "current_state": "${TRACKER_STORY_STATE}",
  "estimate": ${TRACKER_STORY_ESTIMATE},
  "labels": ["needs-pm", "new-cf-dct-release"]
}
EOF
}

set +x

curl -f \
  -H "X-TrackerToken: ${TRACKER_API_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "$(create_tracker_request_body)" \
  "https://www.pivotaltracker.com/services/v5/projects/${TRACKER_PROJECT_ID}/stories"
