#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

echo "======ENVIRONMENT======"
printenv

cd $CF_RELEASE_DIR

gem install bundler

scripts/test
