#!/bin/bash -eux

# shellcheck disable=SC1091
source runtime-ci/tasks/cf-deployment-concourse-tasks/shared-functions

write_uptimer_deploy_config() {
  local deployment_name
  deployment_name=${1}

  local manifest
  manifest=${2}

  set +x
  echo "\"${RUMP_DEPLOYMENTS}\"" | jq --arg cf_api api.${SYSTEM_DOMAIN} \
    --arg admin_password $(bosh int --path=/cf_admin_password vars-store/"${VARS_STORE_FILE}") \
    --arg app_domain ${SYSTEM_DOMAIN} \
    --arg manifest $manifest \
    --arg deployment_name $deployment_name \
    '{
      "while": [
        {
          "command":"bosh",
          "command_args":["-n", "deploy", $manifest, "-d", $deployment_name]
        },
        (split(" ") | .[] |
          {
            "command" :"bosh",
            "command_args": [
              "-n",
              "delete-deployment",
              "-d",
              .
            ]
          }
        )
      ],
      "cf": {
        "api": $cf_api,
        "app_domain": $app_domain,
        "admin_user": "admin",
        "admin_password": $admin_password
      }
    }'
  set -x
}

uptimer_bosh_deploy() {
  local deployment_name
  deployment_name=$(bosh interpolate "${INTERPOLATED_MANIFEST}" --path /name)

  uptimer_config=$(mktemp)
  write_uptimer_deploy_config "${deployment_name}" "${INTERPOLATED_MANIFEST}" > ${uptimer_config}
  local exitStatus
  uptimer -configFile ${uptimer_config}
  exitStatus=$?

  if [ $exitStatus == 64 ]; then
    exit $exitStatus
  fi

  if ${FAIL_ON_DOWNTIME}; then
    exit $exitStatus
  fi
}

function main() {
  check_input_params
  setup_bosh_env_vars
  if ${REGENERATE_VARS_STORE}; then
    remove_vars_store
  fi
  bosh_interpolate
  uptimer_bosh_deploy
}

trap commit_vars_store EXIT

main
