#!/bin/bash
set -exu

pushd merging-repo > /dev/null
  git config user.name "CF MEGA BOT"
  git config user.email "cf-mega@pivotal.io"

  if (env | grep -E '^MERGE_MESSAGE=.*\w+' >/dev/null); then
    git pull --no-ff --no-edit -m "${MERGE_MESSAGE}" ../branch-repo
  else
    git pull --no-edit ../branch-repo
  fi

  git status
  git show --color | cat
popd > /dev/null

shopt -s dotglob
cp -R merging-repo/* merged-repo
