#!/usr/bin/env bash

set -eu

export CF_DEPLOYMENT_NAME=$(jq -r .cf_deployment_name drats-config/drats_integration_config.json)
export BOSH_ENVIRONMENT=$(jq -r .bosh_environment drats-config/drats_integration_config.json)
export BOSH_GW_USER=$(jq -r .bosh_gw_user drats-config/drats_integration_config.json)
export BOSH_GW_HOST=$(jq -r .bosh_gw_host drats-config/drats_integration_config.json)
export BOSH_CLIENT=$(jq -r .bosh_client drats-config/drats_integration_config.json)
export BOSH_CLIENT_SECRET=$(jq -r .bosh_client_secret drats-config/drats_integration_config.json)

export SSH_DESTINATION_CIDR=$(jq -r .ssh_destination_cidr drats-config/drats_integration_config.json)

eval "$(ssh-agent)"

rm -f ~/.gitconfig
jq -r .bosh_gw_private_key drats-config/drats_integration_config.json > ssh.pem
chmod 0400 ssh.pem
ssh-add ssh.pem

sshuttle -r "${BOSH_GW_USER}@${BOSH_GW_HOST}" ${SSH_DESTINATION_CIDR} --daemon -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

sleep 5

jq -r .bosh_ca_cert drats-config/drats_integration_config.json > bosh.cert
export BOSH_CERT_PATH=`pwd`/bosh.cert

pushd bbr-binary-release
  tar xvf *.tar
  export BBR_BUILD_PATH=`pwd`/releases/bbr
popd

${BBR_BUILD_PATH} deployment \
                  --target ${BOSH_ENVIRONMENT} \
                  --ca-cert ${BOSH_CERT_PATH} \
                  --username ${BOSH_CLIENT} \
                  --password ${BOSH_CLIENT_SECRET} \
                  --deployment ${CF_DEPLOYMENT_NAME} \
                  backup-cleanup