---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/relint-base

inputs:
- name: runtime-ci
- name: cf-acceptance-tests
  path: go/src/github.com/cloudfoundry/cf-acceptance-tests

run:
  path: runtime-ci/tasks/run-cats-unit-tests/task
