#!/bin/bash -exu

export GOPATH="$GOPATH:$PWD/go"

pushd go/src/github.com/cloudfoundry/cf-acceptance-tests/helpers
  go run github.com/onsi/ginkgo/v2/ginkgo -r --procs=3 --compilers=3 --randomize-all --randomize-suites --fail-on-pending --keep-going --race --trace
popd
