---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/relint-base

inputs:
- name: runtime-ci
- name: cf-test-helpers

run:
  path: runtime-ci/tasks/run-cf-test-helpers-unit-tests/task
