#!/bin/bash
set -eux

curl  -X POST -H "Content-type: application/json" \
    -d "{
            \"title\": \"$STATE deploying.\",
            \"text\": \"\",
            \"priority\": \"normal\",
            \"tags\": [\"deployment:$EVENT_TAG_DEPLOYMENT\"]
        }" \
"https://app.datadoghq.com/api/v1/events?api_key=$DATADOG_API_KEY"

