#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

root_dir="${PWD}"

# Inputs
RUNTIME_CI_DIR="${root_dir}/${RUNTIME_CI_DIR:?"RUNTIME_CI_DIR must be provided"}"

# Outputs
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?"OUTPUT_DIR must be provided"}"

STEMCELL_VERSION="$(cat aws-stemcell/version)"
echo "REPLACE_WITH_BOSH_STEMCELL_VERSION: '${STEMCELL_VERSION}'" >> deployments-runtime/minimal-aws/manifest_config.yml

ruby \
  "${RUNTIME_CI_DIR}/scripts/ci/template_the_manifest.rb" \
  "cf-release/example_manifests/minimal-aws.yml" \
  "deployments-runtime/minimal-aws/manifest_config.yml" \
  > ${OUTPUT_DIR}/deployment.yml
