---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/relint-base

inputs:
- name: runtime-ci
- name: uptimer

run:
  path: runtime-ci/tasks/run-uptimer-unit-tests/task
