---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/relint-base

inputs:
- name: runtime-ci
- name: uptimer
  path: go/src/github.com/cloudfoundry/uptimer

run:
  path: runtime-ci/tasks/run-uptimer-unit-tests/task
