#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

root_dir="${PWD}"

# Inputs
BOSH_DIRECTOR="${BOSH_DIRECTOR:?"BOSH_DIRECTOR must be provided"}"
BOSH_USER="${BOSH_USER:?"BOSH_USER must be provided"}"

set +x
BOSH_PASSWORD="${BOSH_PASSWORD:?"BOSH_PASSWORD must be provided"}"
set -x

DEPLOYMENT_NAME="${DEPLOYMENT_NAME:?"DEPLOYMENT_NAME must be provided"}"

# Outputs
LOGS_DIR="${root_dir}/${LOGS_DIR}"

bosh -t "$BOSH_DIRECTOR" download manifest "$DEPLOYMENT_NAME" manifest.yml

bosh \
  -n \
  --color \
  -t "$BOSH_DIRECTOR" \
  -d manifest.yml \
  delete deployment "$DEPLOYMENT_NAME"
