#!/bin/bash -exu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function bosh_deploy_nats() {
  pushd stemcell
    bosh upload-stemcell stemcell.tgz
  popd

  pushd nats-release
    local deployment_name
    deployment_name=$(bosh interpolate "example-manifests/nats.yml" --path=/name)
    cat << EOF > create-nats-dev-release.yml
---
- type: replace
  path: /releases/name=nats
  value:
    name: nats
    version: create
    url: file://.
EOF

  interpolated_manifest=$(mktemp)

  bosh \
    -n \
    interpolate \
    --vars-store vars.yml \
    --var-errs \
    example-manifests/nats.yml \
    > $interpolated_manifest

  bosh \
    -n \
    -d "${deployment_name}" \
    deploy $interpolated_manifest \
    --vars-store vars.yml \
    -o create-nats-dev-release.yml

  popd
}

function main() {
  setup_bosh_env_vars
  bosh_deploy_nats
}

trap close_bbl_ssh_connection EXIT

main
