#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

smoke_tests_manifest="${PWD}/${SMOKE_TESTS_MANIFEST}"

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
scripts_dir="$(cd "${my_dir}/../.." && pwd)"

"${scripts_dir}/bosh_setup"

bosh deployment "${smoke_tests_manifest}"

set +e
bosh run errand diego_smoke_tests --download-logs --keep-alive
errand_result=$?
set -e

original_name=$(ls diego_smoke_tests.0.*.tgz)
new_name=$(echo "${original_name}" | sed 's/\.0\./\.0.0.0./')

mv "${original_name}" "smoke-test-results/${new_name}"

exit $errand_result
