#!/bin/bash -exu

set -o pipefail

function main() {
  local root_dir
  root_dir="${1}"

  local copy_manifest
  copy_manifest=false

  local copy_ops
  copy_ops=false

  if [ ! -z "${MANIFEST_NAME}" ] && [ ! -z "${MANIFEST_DESTINATION}" ] ; then
    cp ./manifest/"${MANIFEST_NAME}" ./repo/"${MANIFEST_DESTINATION}"
    copy_manifest=true
  fi

  if [ ! -z "${OPS_FILE_NAME}" ] && [ ! -z "${OPS_FILE_DESTINATION}" ]; then
    cp ./ops-file/"${OPS_FILE_NAME}" ./repo/"${OPS_FILE_DESTINATION}"
    copy_ops=true
  fi

  pushd repo > /dev/null
    if [[ -n $(git status --porcelain) ]]; then
      git config user.name "CF RELINT BOT"
      git config user.email "cf-release-integration@pivotal.io"

      if [ "${copy_manifest}" = true ]; then
        git add ./"${MANIFEST_DESTINATION}"
      fi

      if [ "${copy_ops}" = true ]; then
        git add ./"${OPS_FILE_DESTINATION}"
      fi

      local commit_message
      commit_message=$(cat ${root_dir}/commit-message/${COMMIT_MESSAGE_PATH})

      if [ -z "${commit_message}" ]; then
        commit_message="No changes"
      fi

      git commit -m "${commit_message}"

      git status
      git show --color | cat
    fi
  popd > /dev/null

  shopt -s dotglob
  cp -R repo/* updated-repo
}

main "${PWD}"
