#!/bin/bash
set -exu

export BUNDLE_GEMFILE=runtime-ci/tasks/recreate-datadog-dashboards/Gemfile

bundle install
bundle exec ruby runtime-ci/tasks/recreate-datadog-dashboards/recreate_datadog_dashboards.rb
