#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

cd cf-canaries

# install the canaries application name
bundle
gem build cf_canaries.gemspec
gem install cf_canaries-0.1.3.gem

cf api $CF_API_ENDPOINT
set +x
echo "Authenticating as $CF_API_ADMIN_USER"
cf auth "$CF_API_ADMIN_USER" "$CF_API_ADMIN_PASSWORD"
echo "Succeeded authenticating"
echo "Creating canary user $CF_API_CANARY_USER"
cf create-user "$CF_API_CANARY_USER" "$CF_API_CANARY_PASSWORD"
echo "Succeeded creating user"
set -x

set +e
cf create-org canaries
cf target -o canaries
cf create-space coal-mine
cf target -s coal-mine
cf set-space-role "$CF_API_CANARY_USER" canaries coal-mine SpaceDeveloper
set -e

set +x
echo "Running command:
canaries --number-of-zero-downtime-apps=20 \\
         --number-of-instances-canary-instances=20 \\
         --number-of-instances-per-app=2 \\
         --target=$CF_API_ENDPOINT \\
         --app-domain=$CF_APPS_DOMAIN \\
         --username=$CF_API_CANARY_USER \\
         --password=\$CF_API_CANARY_PASSWORD \\
         --organization=canaries \\
         --space=coal-mine"
canaries --number-of-zero-downtime-apps=20 \
         --number-of-instances-canary-instances=20 \
         --number-of-instances-per-app=2 \
         --target=$CF_API_ENDPOINT \
         --app-domain=$CF_APPS_DOMAIN \
         --username=$CF_API_CANARY_USER \
         --password=$CF_API_CANARY_PASSWORD \
         --organization=canaries \
         --space=coal-mine
echo "Succeeded running command"
set -x
