#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function create_asg_json() {
  local asg_json_path
  asg_json_path=$1

  local instance_group_ips
  instance_group_ips=$(bosh is | grep ${INSTANCE_GROUP_NAME} | awk '{print $4}')

  runtime-ci/tasks/open-asgs-for-bosh-instance-group/write_asgs_json.rb ${instance_group_ips} ${asg_json_path}
}

function main() {
  setup_bosh_env_vars
  local cf_admin_password=$(bosh int vars-store/${VARS_STORE_PATH} --path /cf_admin_password)

  cf api api.${SYSTEM_DOMAIN}
  set +x
    cf auth admin ${cf_admin_password}
  set -x

  local asgs_json=$(mktemp)
  create_asg_json ${asgs_json}

  cf delete-security-group ${SECURITY_GROUP_NAME}
  cf create-security-group ${SECURITY_GROUP_NAME} ${asgs_json}
}

main
