#!/bin/bash -x +e

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

write_uptimer_config() {
  set +x
  echo '{}' | jq --arg cf_api api.${SYSTEM_DOMAIN} \
    --arg admin_password $(bosh int --path=/cf_admin_password vars-store/deployment-vars.yml) \
    --arg app_domain ${SYSTEM_DOMAIN} \
    '{
      "while": {
        "command":"bosh",
        "command_args":["task"]
      },
      "cf": {
        "api": $cf_api,
        "app_domain": $app_domain,
        "admin_user": "admin",
        "admin_password": $admin_password,
        "app_path": "cf-acceptance-tests/assets/dora"
      }
    }'
  set -x
}

function main() {
  setup_bosh_env_vars
  uptimer_config=$(mktemp)
  write_uptimer_config > ${uptimer_config}
  go get -u github.com/cloudfoundry/uptimer
  uptimer -configFile ${uptimer_config}
}

main
