#!/bin/bash

set -xeu

function commit_terraform_state_file {
 git add $1
 git add $2
 git commit -m "Update terraform state file"
}

pushd env-repo
  export GOOGLE_CREDENTIALS=$(cat google_credentials.json)
  pushd terraform
    set +x
    echo 'terraform apply'
    terraform apply
    echo 'commit_terraform_state_file'
    commit_terraform_state_file terraform.tfstate terraform.tfstate.backup
    set -x
    popd

