#!/bin/bash

set -xeu

function commit_terraform_state_file {
  pushd env-repo
    git config user.name "CF MEGA BOT"
    git config user.email "cf-mega@pivotal.io"
    git add .
    git commit -m "Update terraform state file"
  popd

  shopt -s dotglob
  cp -R env-repo/* updated-env-repo/
}

pushd env-repo
  pushd terraform
    export GOOGLE_CREDENTIALS=$(cat google_credentials.json)
    set +x
    echo 'terraform apply'
    terraform apply
    gcloud config set project cf-release-integration-141222
    gcloud config set compute/zone us-west1
    gcloud config set compute/region us-west1-a
    gcloud auth activate-service-account 815441650186-compute@developer.gserviceaccount.com --key-file google_credentials.json
    echo " ********* HEY *********** "
    echo `gcloud compute addresses describe dobby-director-address | grep address: | awk '{print $2}'`
  popd
popd

echo 'commit_terraform_state_file'
commit_terraform_state_file
set -x

