#!/bin/bash

set -eu

echo "Setting target to ${CF_TARGET}"
cf api --skip-ssl-validation "${CF_TARGET}"

echo "Authenticating as ${CF_USER}"
cf auth "${CF_USER}" "${CF_PASSWORD}"

echo "Listing existing feature flags"
cf feature-flags

echo "Enabling diego feature flag"
cf enable-feature-flag diego_docker || true
