#!/bin/bash

set -eu

root_dir="${PWD}"
cf_target=$(cat "${root_dir}/cf-target/${CF_TARGET_PATH:?"\$CF_TARGET_PATH is not set"}")

echo "Setting target to ${cf_target}"
cf api --skip-ssl-validation "${cf_target}"

echo "Authenticating as ${CF_USER}"
cf auth "${CF_USER}" "${CF_PASSWORD}"

echo "Listing existing feature flags"
cf feature-flags

echo "Enabling diego feature flag"
cf enable-feature-flag diego_docker || true
