#!/bin/sh
set -eux

export GOPATH="${PWD}/gopath"
export PATH="${GOPATH}/bin":${PATH}

cd "${GOPATH}/src/github.com/cloudfoundry/runtime-ci"

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

./bin/test
