#!/usr/bin/env bash
set -eux

source tasks/shared-functions

: "${METRIC_TAGS:=""}"

uptimer_result_file=../uptimer-result/${UPTIMER_RESULT_FILE}
if [[ -f "${uptimer_result_file}" ]]; then
  for row in $(echo "${result}" | jq -r '.summaries[] | @base64'); do
      _jq() {
       echo ${row} | base64 --decode | jq -r ${1}
      }

      name=$(_jq '.name')

      export METRIC_NAME="${name}.failed"
      export METRIC_VALUE=$(_jq '.failed')
      emit_metric

      export METRIC_NAME="${name}.total"
      export METRIC_VALUE=$(_jq '.total')
      emit_metric
  done
fi
