#!/bin/bash

cat <<EOF > bosh-lite-diego-cats-manifest/manifest.yml
director_uuid: $(grep director_uuid cf-manifest/"$CF_MANIFEST_PATH" | cut -d' ' -f2)

name: bosh-lite-diego-cats

releases:
- name: cf
  version: latest

networks:
- name: default
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.4.0/30
    reserved:
    - 10.244.4.1
    static: []
  - cloud_properties:
      name: random
    range: 10.244.4.4/30
    reserved:
    - 10.244.4.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.4.8/30
    reserved:
    - 10.244.4.9
    static: []

resource_pools:
- cloud_properties:
    name: random
  env:
    bosh:
      password: \$6\$4gDD3aV0rdqlrKC\$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: xlarge_errand
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

compilation:
  cloud_properties:
    name: random
  network: default
  reuse_compilation_vms: true
  workers: 2

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 3
  serial: false
  update_watch_time: 5000-600000

jobs:
- name: diego-cats
  networks:
  - name: default
  resource_pool: xlarge_errand
  templates:
  - name: acceptance-tests
    release: cf
  instances: 1
  lifecycle: errand
EOF
