#!/bin/bash

cat <<EOF > bosh-lite-diego-cats-manifest/manifest.yml
director_uuid: $(grep director_uuid cf-manifest/"$CF_MANIFEST_PATH" | cut -d' ' -f2)

name: bosh-lite-diego-cats

releases:
- name: cf
  version: latest

networks:
- name: default
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.4.0/30
    reserved:
    - 10.244.4.1
    static:
    - 10.244.4.2
  - cloud_properties:
      name: random
    range: 10.244.4.4/30
    reserved:
    - 10.244.4.5
    static:
    - 10.244.4.6
  - cloud_properties:
      name: random
    range: 10.244.4.8/30
    reserved:
    - 10.244.4.9
    static:
    - 10.244.4.10

resource_pools:
- cloud_properties:
    name: random
  env:
    bosh:
      password: \$6\$4gDD3aV0rdqlrKC\$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: xlarge_errand
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

compilation:
  cloud_properties:
    name: random
  network: cf1
  reuse_compilation_vms: true
  workers: 2

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 3
  serial: false
  update_watch_time: 5000-600000

jobs:
- name: diego-cats
  networks:
  - name: default
  resource_pool: xlarge_errand
  templates:
  - name: acceptance-tests
    release: cf
  instances: 1
  lifecycle: errand

properties:
  acceptance_tests:
    admin_password: admin
    admin_user: admin
    api: api.$(cat bosh-lite-target-file/"$BOSH_LITE_TARGET_FILE_PATH").xip.io
    apps_domain: $(cat bosh-lite-target-file/"$BOSH_LITE_TARGET_FILE_PATH").xip.io
    backend: diego
    client_secret: gorouter-secret
    include_backend_compatibility: true
    include_internet_dependent: true
    include_diego_docker: true
    include_diego_ssh: true
    include_logging: true
    include_route_services: true
    include_routing: true
    include_security_groups: true
    include_services: true
    include_sso: true
    include_v3: true
    nodes: 6
    skip_diego_unsupported_tests: false
    system_domain: $(cat bosh-lite-target-file/"$BOSH_LITE_TARGET_FILE_PATH").xip.io
    use_http: true
EOF
