#!/usr/bin/env bash

set -eu

export CF_DEPLOYMENT_NAME="$(bosh-cli int drats-config/drats_integration_config.json --path=/cf_deployment_name)"
export CF_API_URL="$(bosh-cli int drats-config/drats_integration_config.json --path=/cf_api_url)"
export CF_ADMIN_USERNAME="$(bosh-cli int drats-config/drats_integration_config.json --path=/cf_admin_username)"
export CF_ADMIN_PASSWORD="$(bosh-cli int drats-config/drats_integration_config.json --path=/cf_admin_password)"
export BOSH_ENVIRONMENT="$(bosh-cli int drats-config/drats_integration_config.json --path=/bosh_environment)"
export BOSH_GW_USER="$(bosh-cli int drats-config/drats_integration_config.json --path=/bosh_gw_user)"
export BOSH_GW_HOST="$(bosh-cli int drats-config/drats_integration_config.json --path=/bosh_gw_host)"
export BOSH_GW_PRIVATE_KEY="$(bosh-cli int drats-config/drats_integration_config.json --path=/bosh_gw_private_key)"
export BOSH_CA_CERT="$(bosh-cli int drats-config/drats_integration_config.json --path=/bosh_ca_cert)"
export BOSH_CLIENT="$(bosh-cli int drats-config/drats_integration_config.json --path=/bosh_client)"
export BOSH_CLIENT_SECRET="$(bosh-cli int drats-config/drats_integration_config.json --path=/bosh_client_secret)"

export GOPATH=$PWD
export PATH=$PATH:$GOPATH/bin

eval "$(ssh-agent)"

rm -f ~/.gitconfig
echo "${BOSH_GW_PRIVATE_KEY}" > ssh.pem
chmod 0400 ssh.pem
ssh-add ssh.pem

sshuttle -r "${BOSH_GW_USER}@${BOSH_GW_HOST}" "${SSH_DESTINATION_CIDR}" --daemon -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

sleep 5

echo "$BOSH_CA_CERT" > bosh.cert
export BOSH_CERT_PATH=`pwd`/bosh.cert

pushd bbr-binary-release
  tar xvf *.tar
  export BBR_BUILD_PATH=`pwd`/releases/bbr
popd

pushd src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests
  scripts/run_acceptance_tests.sh
popd