#!/bin/bash
set -exu

root_dir="${PWD}"

# Inputs
DIEGO_RELEASE_DIR="${root_dir}/${DIEGO_RELEASE_DIR:?"\$DIEGO_RELEASE_DIR not set"}"

CF_MANIFEST_PATH="${root_dir}/cf-manifest/${CF_MANIFEST_PATH:?"\$CF_MANIFEST_PATH not set"}"
PROPERTY_OVERRIDES_PATH="${root_dir}/property-overrides/${PROPERTY_OVERRIDES_PATH:?"\$PROPERTY_OVERRIDES_PATH not set"}"
INSTANCE_COUNT_OVERRIDES_PATH="${root_dir}/instance-count-overrides/${INSTANCE_COUNT_OVERRIDES_PATH:?"\$INSTANCE_COUNT_OVERRIDES_PATH not set"}"
RELEASE_VERSIONS_PATH="${root_dir}/release-versions/${RELEASE_VERSIONS_PATH:?"\$RELEASE_VERSIONS_PATH not set"}"
IAAS_SETTINGS_PATH="${root_dir}/iaas-settings/${IAAS_SETTINGS_PATH:?"\$IAAS_SETTINGS_PATH not set"}"
DIEGO_SQL_RESOURCE_PATH="${root_dir}/${DIEGO_SQL_RESOURCE_PATH:?"\$DIEGO_SQL_RESOURCE_PATH not set"}"

# Outputs
GENERATED_DIEGO_MANIFEST_DIR="${root_dir}/${GENERATED_DIEGO_MANIFEST_DIR:?"\$GENERATED_DIEGO_MANIFEST_DIR not set"}"

pushd "${DIEGO_RELEASE_DIR}"
  ./scripts/generate-deployment-manifest \
    -c "${CF_MANIFEST_PATH}" \
    -i "${IAAS_SETTINGS_PATH}" \
    -p "${PROPERTY_OVERRIDES_PATH}" \
    -n "${INSTANCE_COUNT_OVERRIDES_PATH}" \
    -v "${RELEASE_VERSIONS_PATH}" \
    -s "${DIEGO_SQL_RESOURCE_PATH}" \
    $([ "${USE_LOCKET}" == "true" ] && echo "-Q") \
    -x \
    -r \
    > "${GENERATED_DIEGO_MANIFEST_DIR}/diego-deployment.yml"
popd
