#!/bin/bash
set -exu

# Inputs
SUITE_NAME="${SUITE_NAME:?"\$SUITE_NAME not set"}"
API="${API:?"\$API not set"}"
APPS_DOMAIN="${APPS_DOMAIN:?"\$APPS_DOMAIN not set"}"
SKIP_SSL_VALIDATION="${SKIP_SSL_VALIDATION:?"\$SKIP_SSL_VALIDATION not set"}"
CF_USER="${CF_USER:?"\$CF_USER not set"}"
ORG="${ORG:?"\$ORG not set"}"
SPACE="${SPACE:?"\$SPACE not set"}"
USE_EXISTING_ORG="${USE_EXISTING_ORG:?"\$USE_EXISTING_ORG not set"}"

set +x
CF_PASSWORD="${CF_PASSWORD:?"\$CF_PASSWORD not set"}"
set -x

set +x
cat > config.json <<EOF
{
    "suite_name": "$SUITE_NAME",
    "api": "$API",
    "apps_domain": "$APPS_DOMAIN",
    "skip_ssl_validation": $SKIP_SSL_VALIDATION,
    "user": "$CF_USER",
    "password": "$CF_PASSWORD",
    "org": "$ORG",
    "space": "$SPACE",
    "use_existing_org": $USE_EXISTING_ORG
}
EOF
set -x
export CONFIG=$PWD/config.json

echo "======TEST======"
cd smoke-tests

set +e
./bin/test -v -trace $ARGS > output.log
EXITSTATUS=$?

if [[ $EXITSTATUS -ne 0 ]]; then
    echo "======Output====="
    cat output.log

    echo "======TRACE======"
    cat smoke/results/CF-TRACE*
fi

exit $EXITSTATUS
