#!/bin/bash
set -xeu

export CONFIG
CONFIG="$PWD/integration-config/${CONFIG_FILE_PATH}"

echo "Moving cf-routing-acceptance-tests onto the gopath..."
mkdir -p $GOPATH
cd routing-release/src/code.cloudfoundry.org
rm -rf routing-acceptance-tests
git clone https://github.com/cloudfoundry-incubator/routing-acceptance-tests.git
cd -

cp -R routing-release/src $GOPATH

go install github.com/onsi/ginkgo/ginkgo

cd ${GOPATH}/src/code.cloudfoundry.org/routing-acceptance-tests

packages=("http_routes" "tcp_routing" "smoke_test")
for i in "${packages[@]}"
do
  ginkgo -r "$i" \
    -slowSpecThreshold=120 \
    -keepGoing \
    -randomizeAllSpecs \
    -skipPackage=helpers \
    -slowSpecThreshold=120 \
    -nodes="${NODES}"
done
