#!/bin/bash
set -xeu

export CONFIG
CONFIG="$PWD/integration-config/${CONFIG_FILE_PATH}"

GOPATH=/go/src
export GOPATH

echo "Moving cf-routing-acceptance-tests onto the gopath..."
mkdir -p $GOPATH
cp -R routing-release/src $GOPATH

cd ${GOPATH}/code.cloudfoundry.org/routing-acceptance-tests

packages=("http_routes" "tcp_routing")
for i in "${packages[@]}"
do
  ginkgo -r "$i" \
    -slowSpecThreshold=120 \
    -keepGoing \
    -randomizeAllSpecs \
    -skipPackage=helpers \
    -slowSpecThreshold=120 \
    -nodes="${NODES}"
done
