#!/bin/bash
set -exu

BOSH_TARGET=$(cat "bosh-target/${BOSH_TARGET_FILE}")
BOSH_USER=$(cat bosh-username/"${BOSH_USER_FILE:?"Path to BOSH_USER_FILE must be provided"}")

set +x
BOSH_PASSWORD=$(cat "bosh-password/${BOSH_PASSWORD_FILE?"Path to BOSH_PASSWORD_FILE must be provided"}")
echo bosh -u "${BOSH_USER}" -p REDACTED target "$BOSH_TARGET"
bosh -u "${BOSH_USER}" -p "${BOSH_PASSWORD}" target "$BOSH_TARGET"
set -x

bosh status
director_version=$(bosh status | grep Version | tr -s ' ' | cut -f3 -d' ')
echo "$director_version" > director-version/director_version
