#!/bin/bash
set -exu

DEPLOYMENT_NAME="${DEPLOYMENT_NAME:?"DEPLOYMENT_NAME must be provided"}"

export BOSH_CA_CERT=ca-cert/${CA_CERT_FILE}

export BOSH_ENVIRONMENT=$(cat target/${TARGET_FILE})

export BOSH_USER=$(cat username/${USERNAME_FILE})

set +x
export BOSH_PASSWORD=$(cat password/${PASSWORD_FILE})
set -x

bosh \
  -n \
  delete-deployment -d ${DEPLOYMENT_NAME}

bosh \
  -n \
  clean-up --all
