#!/bin/bash
set -exu

DEPLOYMENT_NAME="${DEPLOYMENT_NAME:?"DEPLOYMENT_NAME must be provided"}"

export BOSH_CA_CERT=env-repo/infrastructure/bosh/certs/rootCA.pem

export BOSH_ENVIRONMENT=$(cat env-repo/infrastructure/bosh/bosh-target)

export BOSH_USER=$(cat env-repo/infrastructure/bosh/username)

set +x
export BOSH_PASSWORD=$(cat env-repo/infrastructure/bosh/password)
set -x

bosh \
  -n \
  delete-deployment -d ${DEPLOYMENT_NAME}
