#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

curl -X PUT "$URL/no" -d "token=$TOKEN" -d "reason=$REASON" -d "buildnumber=0"

