#!/bin/bash
set -eux

DEPLOYMENT_VAR_FILE="${DEPLOYMENT_VAR_FILE:?"DEPLOYMENT_VAR_FILE must be provided"}"
DEPLOYMENT_OPS_FILE="${DEPLOYMENT_OPS_FILE:?"DEPLOYMENT_OPS_FILE must be provided"}"

pushd env-repo
  pushd terraform
    set +x
    gcloud config set project cf-release-integration-141222
    gcloud config set compute/region us-west1
    gcloud config set compute/zone us-west1
    gcloud auth activate-service-account 815441650186-compute@developer.gserviceaccount.com --key-file google_credentials.json
  popd
popd
set -x

export BOSH_USER=$(cat username/"${USERNAME_FILE}")
BOSH_MANIFEST="env-repo/bosh-init/manifest.yml"
set +x

export BOSH_PASSWORD=$(cat "password/${PASSWORD_FILE}")
export BOSH_CA_CERT="ca-cert/${CA_CERT_FILE}"
set +u
set -u

bosh create-env -n ${BOSH_MANIFEST} --var-files=env-repo/${DEPLOYMENT_VAR_FILE} --ops-file=${DEPLOYMENT_OPS_FILE}
