#!/bin/bash
set -eux

root_dir="${PWD}"

# Outputs
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?"\$OUTPUT_DIR not set"}"

source ~/.bashrc

set -u

cd cf-release

./scripts/generate_deployment_manifest \
  "${INFRASTRUCTURE}" \
  "../deployments-runtime/${ENVIRONMENT}/stubs/cf/"*.yml > "${OUTPUT_DIR}/deployment.yml"

