#!/bin/sh
set -eux

last_version=$(cat cf-bosh-io-release/version)
last_tag="v${last_version}"
next_tag=v$((${last_version} + 1))
issue_title="CF ${next_tag}"

cd cf-release-release-candidate
  rc_sha=$(git show-ref release-candidate -s --heads)
cd ..

comment_body="cf-release Release Candidate SHA for ${next_tag}:
[${rc_sha}](https://github.com/cloudfoundry/cf-release/commit/${rc_sha})

**Please read these instructions, as they changed on 4 Nov 2015.**
- Edit this comment by setting the approval for your section (delete the thumb you don't want)
- Also set your GitHub handle as the approver
- Add any additional comments you may have in your section
- If you notice you are the last person to set your approval, as a courtesy please also add a new comment to the issue saying so, so that we get GitHub notifications that all approvals are done.

----
@Amit-PivotalLabs, @robdimsdale:
Does this cf-release SHA look good for the release integration team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@Amit-PivotalLabs, @zankich:
Does this cf-release SHA look good for the infrastructure team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@shalako, @crhino:
Does this cf-release SHA look good for the routing team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@sreetummidi, @mbhave:
Does this cf-release SHA look good for the identity team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@Jim-Campbell, @wfernandes:
Does this cf-release SHA look good for the Loggregator team? Do the a1 logging metrics look nominal?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@SocalNick, @utako:
Does this cf-release SHA look good for the CAPI team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@Dannyzen, @jvshahid:
Does this cf-release SHA look good for the Buildpacks and Stacks team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@nebhale, @cgfrost:
Does this cf-release SHA look good for the Java Buildpack team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@ematpl, @jfmyers9:
Can you provide a compatible diego-release SHA?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@fraenkel, @sykesm:
Does this cf-release SHA look good for the DEA + HM9000 team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
"

echo "Finding cf-final-release-election issue number"
set +x
	issue_number=$(curl -s -f "https://api.github.com/repos/cloudfoundry/cf-final-release-election/issues?access_token=${GH_ACCESS_TOKEN}" \
		| jq "map(select(.title == $(echo $issue_title | jq -R .)))[0].number")
set -x

if [ "${issue_number}" = "null" ]; then
    echo "Issue ${issue_title} does not exist, will create"

	echo "Creating cf-final-release-election issue"
	set +x
		curl -f "https://api.github.com/repos/cloudfoundry/cf-final-release-election/issues?access_token=${GH_ACCESS_TOKEN}" \
			-X POST	\
			-d "{\"title\": \"${issue_title}\", \"body\": $(echo "$comment_body" | jq -s -R .)}"
	set -x
	echo "Succeeded creating cf-final-release-election issue"
else
    echo "Succeeded finding cf-final-release-election issue number: $issue_number"

	echo "Posting cf-final-release-election issue comment"
	set +x
		curl -f "https://api.github.com/repos/cloudfoundry/cf-final-release-election/issues/${issue_number}/comments?access_token=${GH_ACCESS_TOKEN}" \
			-X POST	\
			-d "{\"body\": $(echo "$comment_body" | jq -s -R .)}"
	set -x
	echo "Succeeded posting cf-final-release-election issue comment"
fi

