#!/bin/sh
set -eux

last_version=$(cat cf-bosh-io-release/version)
last_tag="v${last_version}"
next_tag=v$((${last_version} + 1))
issue_title="CF ${next_tag}"

cd cf-release-release-candidate
  rc_sha=$(git show-ref release-candidate -s --heads)
cd ..

comment_body="cf-release Release Candidate SHA for ${next_tag}:
[${rc_sha}](https://github.com/cloudfoundry/cf-release/commit/${rc_sha})

**Please read these instructions, as they changed on 4 Nov 2015.**
- Edit this comment by setting the approval for your section (delete the thumb you don't want)
- Also set your GitHub handle as the approver
- Add any additional comments you may have in your section
- If you notice you are the last person to set your approval, as a courtesy please also add a new comment to the issue saying so, so that we get GitHub notifications that all approvals are done.

----
@dsabeti, @staylor14:
Does this cf-release SHA look good for the release integration team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@evanfarrar, @christianang:
Does this cf-release SHA look good for the infrastructure team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@valeriap, @smoser-ibm:
Does this cf-release SHA look good for the postgres-release team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@shalako, @shashwathi:
Does this cf-release SHA look good for the routing team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@sreetummidi, @plfx:
Does this cf-release SHA look good for the identity team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@ahevenor, @jasonkeene:
Does this cf-release SHA look good for the Loggregator team? Do the a1 logging metrics look nominal?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@zrob, @gerg:
Does this cf-release SHA look good for the CAPI team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@sclevine, @dgodd:
Does this cf-release SHA look good for the Buildpacks and Stacks team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@nebhale, @cgfrost:
Does this cf-release SHA look good for the Java Buildpack team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@ematpl, @jvshahid:
Can you provide a compatible diego-release SHA or final release version?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@rusha19, @jaydunk:
Can you provide a compatible cf-networking-release SHA or final release version?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@glestaris, @spikymonkey:
Can you provide a compatible grootfs-release SHA or final release version?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
"

echo "Finding cf-final-release-election issue number"
set +x
	issue_number=$(curl -s -f "https://api.github.com/repos/cloudfoundry/cf-final-release-election/issues?access_token=${GH_ACCESS_TOKEN}" \
		| jq "map(select(.title == $(echo $issue_title | jq -R .)))[0].number")
set -x

if [ "${issue_number}" = "null" ]; then
    echo "Issue ${issue_title} does not exist, will create"

	echo "Creating cf-final-release-election issue"
	set +x
		output=$(curl -f "https://api.github.com/repos/cloudfoundry/cf-final-release-election/issues?access_token=${GH_ACCESS_TOKEN}" \
			-X POST	\
			-d "{\"title\": \"${issue_title}\", \"body\": $(echo "$comment_body" | jq -s -R .)}")
		echo $output
	set -x
	echo "Succeeded creating cf-final-release-election issue"
else
    echo "Succeeded finding cf-final-release-election issue number: $issue_number"

	echo "Posting cf-final-release-election issue comment"
	set +x
		output=$(curl -f "https://api.github.com/repos/cloudfoundry/cf-final-release-election/issues/${issue_number}/comments?access_token=${GH_ACCESS_TOKEN}" \
			-X POST	\
			-d "{\"body\": $(echo "$comment_body" | jq -s -R .)}")
		echo $output
	set -x
	echo "Succeeded posting cf-final-release-election issue comment"
fi

issue_url=$(echo $output | jq .html_url)
echo "Hey there <@dsabeti> <@staylor>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/release-integration
echo "Hey there <@efarrar> <@genevieve>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/infrastructure
echo "Hey there <@valepert> <@smoser>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/postgres-release
echo "Hey there <@shannon> <@sreddy>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/routing
echo "Hey there <@stummidi> <@jeremy>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/uaa
echo "Hey there <@hev> <@jasonkeene>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/loggregator
echo "Hey there <@zach> <@gerg>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/capi
echo "Hey there <@slevine> <@dgoddard>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/buildpacks
echo "Hey there <@emalm> <@jvshahid>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/diego
echo "Hey there <@uramachandran> <@ldunkelberger>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/container-networking
echo "Hey there <@glestaris> <@gareth>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/grootfs

echo "Successfully saved a Slack messages"

