#!/bin/bash
set -eu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

if [ -z "${VARS_STORE_PATH}" ]; then
  setup_bosh_env_vars
  CF_PASSWORD=$(get_password_from_credhub cf_admin_password)
else
  CF_PASSWORD=$(bosh interpolate vars-store/${VARS_STORE_PATH} --path=/cf_admin_password)
fi

echo "Setting target to api.${SYSTEM_DOMAIN}"
cf api --skip-ssl-validation api.${SYSTEM_DOMAIN}

echo "Authenticating as admin"
cf auth admin "${CF_PASSWORD}"

echo "Creating tcp domain"
cf create-shared-domain tcp.${SYSTEM_DOMAIN} --router-group default-tcp || true
