#!/bin/bash
set -eu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

setup_bosh_env_vars
setup_password_from_credhub cf_admin_password

echo "Setting target to api.${SYSTEM_DOMAIN}"
cf api --skip-ssl-validation api.${SYSTEM_DOMAIN}

echo "Authenticating as admin"
set +x
  cf auth admin "${cf_admin_password}"
set -x

echo "Creating tcp domain"
cf create-shared-domain tcp.${SYSTEM_DOMAIN} --router-group default-tcp || true
