#!/bin/bash -eux

root_dir="${PWD}"

export GOPATH="${root_dir}/go"
export PATH=$GOPATH/bin:$PATH

mkdir -p "${GOPATH}/src/github.com/pivotal-cf-experimental"
ln -s "${root_dir}/chore-bot-source" "${GOPATH}/src/github.com/pivotal-cf-experimental/relint-trackerbot"

go get github.com/onsi/ginkgo/...

pushd "${GOPATH}/src/github.com/pivotal-cf-experimental/relint-trackerbot" > /dev/null
  ginkgo -r -randomizeSuites -randomizeAllSpecs
popd > /dev/null
