#!/bin/bash
set -eux

pushd pull-request-comment > /dev/null
  echo "Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:" \
  > comment
popd > /dev/null