#!/bin/bash
set -eux

apt-get install -y bc

pushd pull-request-comment > /dev/null
  echo "Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:" \
  > comment

  uptimer_result_file=../uptimer-result/${UPTIMER_RESULT_FILE}
  if [[ -f "${uptimer_result_file}" ]]; then
    echo -e "\nUptimer Results:" >> comment

    result=$(cat ${uptimer_result_file})
    commandExitCode=$(echo "${result}" | jq -r '.commandExitCode')
    if [[ "${commandExitCode}" == "0" ]]; then
      echo "PASSED: Deploy command succeeded" >> comment
    else
      echo "FAILED: Deploy command exit code: ${commandExitCode}" >> comment
    fi

    for row in $(echo "${result}" | jq -r '.summaries[] | @base64'); do
        _jq() {
         echo ${row} | base64 --decode | jq -r ${1}
        }

        failed=$(_jq '.failed')
        allowedFailures=$(_jq '.allowedFailures')
        isFailedResult=false
        if (( ${failed} > ${allowedFailures} )); then
          isFailedResult=true
        fi

        total=$(_jq '.total')
        if [[ "${total}" == "0" ]]; then
          failureRate=0
        else
          failureRate=$(echo "scale=2;$failed/$total" | bc)
        fi

        if ${isFailedResult}; then
          echo "FAILED: ($(_jq '.name')): $(_jq '.failed') failed attempts to $(_jq '.summaryPhrase') with a threshold of $(_jq '.allowedFailures') allowed failures (Total attempts: $(_jq '.total'), failure rate ${failureRate}))%" >> comment
        else
          echo "PASSED: ($(_jq '.name')): $(_jq '.failed') failed attempts to $(_jq '.summaryPhrase') with a threshold of $(_jq '.allowedFailures') allowed failures (Total attempts: $(_jq '.total'))" >> comment
        fi
    done
  fi

popd > /dev/null