---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/relint-base

inputs:
- name: runtime-ci
- name: pull-request
- name: uptimer-result
  optional: true

outputs:
- name: pull-request-comment

params:
  UPTIMER_RESULT_FILE: result.json

run:
  path: runtime-ci/tasks/write-pr-check-failure-comment/task
