#!/bin/bash -exu

function update_release() {
  local release_name
  release_name="$1"
  local compiled_release_ops_file
  compiled_release_ops_file="$2"
  local release_sha
  release_sha=$(sha1sum compiled-release-tarball/*.tgz | awk '{print $1}')
  local release_tarball
  pushd compiled-release-tarball
    release_tarball=$(ls *.tgz)
  popd
  local release_version
  release_version=$(cat bosh-io-release/version)

  update_release_ops_file=$(mktemp)

(
cat << EOF
---
- type: replace
  path: /path=~1releases~1name=${release_name}~1url
  value:
  - type: replace
    path: /releases/name=cf-mysql/url
    value: https://storage.googleapis.com/cf-deployment-compiled-releases/${release_tarball}
- type: replace
  path: /path=~1releases~1name=${release_name}~1version
  value:
  - type: replace
    path: /releases/name=cf-mysql/version
    value: "${release_version}"
- type: replace
  path: /path=~1releases~1name=${release_name}~1sha1
  value:
  - type: replace
    path: /releases/name=cf-mysql/sha1
    value: "${release_sha}"
EOF
) > $update_release_ops_file

  bosh interpolate $compiled_release_ops_file -o $update_release_ops_file
}

function main() {
  update_release $RELEASE_NAME ops-files/operations/use-compiled-releases.yml > updated-compiled-releases-ops-file/use-compiled-releases.yml
}

main
