#!/usr/bin/env bash

set -eu

pushd env-repo/"${BBL_STATE_DIR}" > /dev/null
  BOSH_ENVIRONMENT=$(bbl director-address)
  BOSH_GW_PRIVATE_KEY="$(bbl ssh-key)"
  BOSH_GW_HOST=$(bbl jumpbox-address)
  BOSH_CA_CERT=$(bbl director-ca-cert)
  BOSH_CLIENT=$(bbl director-username)
  BOSH_CLIENT_SECRET=$(bbl director-password)
popd > /dev/null

echo '{}' | jq \
--arg cf_deployment_name ${DEPLOYMENT_NAME} \
--arg cf_api_url "https://api.${SYSTEM_DOMAIN}" \
--arg cf_admin_password $(bosh interpolate vars-store/${VARS_STORE_FILE} --path=/cf_admin_password) \
--arg bosh_environment "${BOSH_ENVIRONMENT}" \
--arg bosh_gw_host "${BOSH_GW_HOST}" \
--arg bosh_gw_private_key "${BOSH_GW_PRIVATE_KEY}" \
--arg bosh_ca_cert "${BOSH_CA_CERT}" \
--arg bosh_client "${BOSH_CLIENT}" \
--arg bosh_client_secret "${BOSH_CLIENT_SECRET}" \
--arg ssh_destination_cidr "${SSH_DESTINATION_CIDR}" \
--arg nfs_broker_password $(bosh interpolate vars-store/${VARS_STORE_FILE} --path=/nfs-broker-password) \
--arg nfs_broker_url "http://nfs-broker.${SYSTEM_DOMAIN}" \
'{
    "cf_deployment_name": $cf_deployment_name,
    "cf_api_url": $cf_api_url,
    "cf_admin_username": "admin",
    "cf_admin_password": $cf_admin_password,
    "bosh_environment": $bosh_environment,
    "bosh_gw_user": "jumpbox",
    "bosh_gw_host": $bosh_gw_host,
    "bosh_gw_private_key": $bosh_gw_private_key,
    "bosh_ca_cert": $bosh_ca_cert,
    "bosh_client": $bosh_client,
    "bosh_client_secret": $bosh_client_secret,
    "ssh_destination_cidr": $ssh_destination_cidr,
    "nfs_service_name": "nfs",
    "nfs_plan_name": "Existing",
    "nfs_broker_user": "nfs-broker",
    "nfs_broker_password": $nfs_broker_password,
    "nfs_broker_url": $nfs_broker_url
}' > drats-config/drats_integration_config.json
