#!/usr/bin/env bash

set -eu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

setup_bosh_env_vars
pushd bbl-state/"${BBL_STATE_DIR}" > /dev/null
  BOSH_GW_PRIVATE_KEY="$(bbl ssh-key)"
  BOSH_GW_HOST=$(bbl jumpbox-address)
popd > /dev/null

cf_admin_password=$(get_password_from_credhub "cf_admin_password")
nfs_broker_password=$(get_password_from_credhub "nfs-broker-password")

echo '{}' | jq \
--arg cf_deployment_name ${DEPLOYMENT_NAME} \
--arg cf_api_url "https://api.${SYSTEM_DOMAIN}" \
--arg cf_admin_password ${cf_admin_password} \
--arg bosh_environment "${BOSH_ENVIRONMENT}" \
--arg bosh_gw_host "${BOSH_GW_HOST}" \
--arg bosh_gw_private_key "${BOSH_GW_PRIVATE_KEY}" \
--arg bosh_ca_cert "${BOSH_CA_CERT}" \
--arg bosh_client "${BOSH_CLIENT}" \
--arg bosh_client_secret "${BOSH_CLIENT_SECRET}" \
--arg ssh_destination_cidr "${SSH_DESTINATION_CIDR}" \
--arg nfs_broker_password ${nfs_broker_password} \
--arg nfs_broker_url "http://nfs-broker.${SYSTEM_DOMAIN}" \
'{
    "cf_deployment_name": $cf_deployment_name,
    "cf_api_url": $cf_api_url,
    "cf_admin_username": "admin",
    "cf_admin_password": $cf_admin_password,
    "bosh_environment": $bosh_environment,
    "bosh_client": $bosh_client,
    "bosh_client_secret": $bosh_client_secret,
    "bosh_ca_cert": $bosh_ca_cert,
    "ssh_proxy_user": "jumpbox",
    "ssh_proxy_host": $bosh_gw_host,
    "ssh_proxy_cidr": $ssh_destination_cidr,
    "ssh_proxy_private_key": $bosh_gw_private_key,
    "nfs_service_name": "nfs",
    "nfs_plan_name": "Existing",
    "nfs_broker_user": "nfs-broker",
    "nfs_broker_password": $nfs_broker_password,
    "nfs_broker_url": $nfs_broker_url,
    "timeout_in_minutes": 30,
    "delete_and_redeploy_cf": false,
    "include_cf-app": true,
    "include_cf-networking": true,
    "include_cf-uaa": true,
    "include_cf-credhub": false,
    "include_cf-routing": true,
    "include_app-uptime": true,
    "include_cf-nfsbroker": true
}' > drats-config/drats_integration_config.json
