#!/bin/bash
set -e -x

source ~/.bashrc

pushd $TARBALL_DIR
  TARBALL_NAME=$(pwd)/$(ls | grep .tgz)
popd

cp runtime-credentials/cf-release/private.yml ${CF_RELEASE_DIR}/config/

mkdir -p release_output

pushd $CF_RELEASE_DIR
  echo "Creating final release"
  bosh finalize release $TARBALL_NAME

  new_cf_release=$(find releases -regex ".*cf-[0-9]*.yml" | sort | tail -n 1 | egrep -o 'cf-[0-9]+' | egrep -o '[0-9]+')

  git add .final_builds releases
  git config user.name "Runtime CI"
  git config user.email "cf-runtime-eng+ci@pivotal.io"
  git commit -m "Final release ${new_cf_release}"
  commit_sha=$(git rev-parse HEAD)

  git branch -D master_release_test
  git checkout master_release_test
  git merge --ff-only ${commit_sha}

  echo ${new_cf_release} > version_number
popd

rm ${CF_RELEASE_DIR}/config/private.yml
