#!/bin/bash

set -eux

build_name=$(cat acceptance-test-metadata/build-name)
build_job_name=$(cat acceptance-test-metadata/build-job-name)
atc_external_url=$(cat acceptance-test-metadata/atc-external-url)
build_pipeline_name=$(cat acceptance-test-metadata/build-pipeline-name)

build_url="${atc_external_url}/pipelines/${build_pipeline_name}/jobs/${build_job_name}/builds/${build_name}"
echo "$build_url" > build_url/build_url
