---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
- name: runtime-ci  # - This repo
- name: cf-deployment-concourse-tasks
- name: bbl-state   # - The env repo containing the Director's bbl state dir
- name: pool-lock
  optional: true

outputs:
- name: updated-bbl-state
# - The bbl-state resource, with changes git committed,
#   ready to be `put` to a git resource.
# - This output _must_ be persisted for these tasks to function properly

run:
  path: runtime-ci/tasks/bbl-cleanup-leftovers/task

params:
  BBL_STATE_DIR: bbl-state
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to the `bbl-state` input
  # - If blank or '.', uses `bbl-state` input as the location for bbl state

  GIT_COMMIT_EMAIL: "cf-release-integration@pivotal.io"
  GIT_COMMIT_USERNAME: "CI Bot"
  # - Optional
  # - You may choose the git committer username and email address by setting these

  # AWS Configuration Params
  # - Required for AWS
  BBL_AWS_ACCESS_KEY_ID:
  BBL_AWS_SECRET_ACCESS_KEY:

  # Azure Configuration Params
  # - Required for Azure
  BBL_AZURE_CLIENT_ID:
  BBL_AZURE_CLIENT_SECRET:
  BBL_AZURE_TENANT_ID:
  BBL_AZURE_SUBSCRIPTION_ID:

  # GCP Configuration Params
  # - Required for GCP
  BBL_GCP_SERVICE_ACCOUNT_KEY:
  # - Key content or path to the file containing credentials downloaded from GCP
  # - Path is relative to the `bbl-state` input

  STORE_BBL_STATE_AS_TARBALL: false
  # - Optional
  # - Creates a tarball of the bbl-state directory, instead of treating it
  # - as a git repo and committing.
  # - This is useful if you want to store your state file in S3 or GCS.

  BBL_ENV_NAME:
  # - Optional
  # - A label to apply to the bbl environment
  # - Label will appear in the IaaS metadata/interface

  BBL_JSON_CONFIG:
  # - Optional
  # - For if you need a dynamic config for BBL
