#!/bin/bash -exu

function main() {
  local root_dir
  root_dir="${1}"

  export GOPATH="${root_dir}/go"

  pushd "${GOPATH}/src/github.com/cloudfoundry/runtime-ci/util/update-manifest-releases"
    go get github.com/onsi/ginkgo/...
    ginkgo -r -randomizeSuites -randomizeAllSpecs .
  popd
}

main "${PWD}"
