#!/bin/bash -exu

function main() {
  local root_dir
  root_dir="${1}"

  pushd "${root_dir}/runtime-ci/util/update-manifest-releases"
    go install github.com/onsi/ginkgo/...@latest
    ginkgo -r -randomizeSuites -randomizeAllSpecs .
  popd
}

main "${PWD}"
