---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: runtime-ci
- name: cf-deployment # repo containing the original manifest
- name: release
- name: stemcell

outputs:
- name: updated-cf-deployment

run:
  path: runtime-ci/tasks/update-single-manifest-release/task

params:
  COMMIT_MESSAGE_PATH: commit-message.txt
  ORIGINAL_DEPLOYMENT_MANIFEST_PATH: cf-deployment.yml
  UPDATED_DEPLOYMENT_MANIFEST_PATH: cf-deployment.yml
  RELEASE_NAME:
