---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: runtime-ci
  path: go/src/github.com/cloudfoundry/runtime-ci
- name: deployment-configuration # repo containing the original manifest
- name: release
- name: stemcell

outputs:
- name: updated-deployment-manifest

run:
  path: go/src/github.com/cloudfoundry/runtime-ci/tasks/update-single-manifest-release/task

params:
  COMMIT_MESSAGE_PATH: commit-message.txt
  ORIGINAL_DEPLOYMENT_MANIFEST_PATH: cf-deployment.yml
  UPDATED_DEPLOYMENT_MANIFEST_PATH: cf-deployment.yml
  RELEASE_NAME:
