#!/bin/bash -exu

function main() {
  local root_dir
  root_dir="${1}"

  export GOPATH="${root_dir}/go"
  export PATH=$GOPATH/bin:$PATH

  ln -s release "${RELEASE_NAME}-release"

  cp -r deployment-configuration/* updated-deployment-manifest

  pushd "${GOPATH}/src/github.com/cloudfoundry/runtime-ci/util/update-manifest-releases"
    go run main.go --build-dir "${root_dir}" --release "${RELEASE_NAME}" --target manifest
  popd
}

main "${PWD}"
