#!/bin/bash
set -eux

function setup_bosh_env_vars() {
  set +x
  pushd bbl-state/"${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd
  set -x
}

function close_bbl_ssh_connection() {
  pkill ssh || true
}

function update_cloud_config() {
  bosh \
    -n \
    update-cloud-config \
    "cloud-config/${CLOUD_CONFIG_FILE}"
}

function main() {
  setup_bosh_env_vars
  update_cloud_config
  close_bbl_ssh_connection
}

main

