---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: runtime-ci
- name: bbl-state

outputs:
- name: updated-bbl-state

run:
  path: runtime-ci/tasks/generate-external-ip-db-vars/task

params:
  BBL_STATE_DIR: bbl-state
  VARS_DIR: bbl-state
