#!/usr/bin/env bash

set -eux

root_dir=${PWD}
VARIABLE_DIR=${root_dir}/bbl-state/${VARS_DIR}

cd bbl-state/$BBL_STATE_DIR
  set +x

  echo "Grabbing public ips"
  PUBLIC_IP_OUTPUT=$(bbl outputs | grep public_ip || true)
  if [[ -n "${PUBLIC_IP_OUTPUT}" ]]; then
    echo "Outputting public ips ${PUBLIC_IP_OUTPUT} to ${VARIABLE_DIR}/external-public-ip-vars.yml"
    echo "${PUBLIC_IP_OUTPUT}" > "${VARIABLE_DIR}/external-public-ip-vars.yml"
  else
    echo "No public_ip outputs found; skipping write to ${VARIABLE_DIR}/external-public-ip-vars.yml"
  fi

  echo "Grabbing DB HOST"
  DB_HOST=$(bbl outputs | grep db_host | awk '{print $2}')

  echo "Outputting db host ${DB_HOST} to ${VARIABLE_DIR}/external-db-host-vars.yml"
  rm -f ${VARIABLE_DIR}/external-db-host-vars.yml
  for key in {cc,uaa,bbs,routing_api,policy_server,silk_controller,locket,credhub}; do
    echo "external_${key}_database_address: ${DB_HOST}" >> ${VARIABLE_DIR}/external-db-host-vars.yml;
  done

  set -x
cd $root_dir

cp -r bbl-state/. updated-bbl-state
