#!/bin/bash -exu

ops_file_to_update() {
  local release_name
  release_name="${1}"
  local release_sha
  release_sha=$(sha1sum ${release_name}-release-tarball/*.tgz | awk '{print $1}')
  local release_tarball
  pushd ${release_name}-release-tarball
    # shellcheck disable=SC2035
    release_tarball=$(ls *.tgz)
  popd
  local release_version
  release_version=$(cat ${release_name}-release/version)

cat << EOF
- type: replace
  path: /path=~1releases~1name=${release_name}~1url?
  value:
    type: replace
    path: /releases/name=${release_name}/url
    value: https://storage.googleapis.com/cf-deployment-compiled-releases/${release_tarball}
- type: replace
  path: /path=~1releases~1name=${release_name}~1version?
  value:
    type: replace
    path: /releases/name=${release_name}/version
    value: "${release_version}"
- type: replace
  path: /path=~1releases~1name=${release_name}~1sha1?
  value:
    type: replace
    path: /releases/name=${release_name}/sha1
    value: "${release_sha}"
EOF
}

main() {
  local update_release_ops_file
  update_release_ops_file=$(mktemp)
  echo "---" > ${update_release_ops_file}
  ops_file_to_update capi >> ${ops_file}
  ops_file_to_update cf-mysql >> ${ops_file}
  bosh interpolate ops-files/operations/use-compiled-releases.yml -o "${update_release_ops_file}" \
    > updated-compiled-releases-ops-file/use-compiled-releases.yml
}

main
