#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

# Inputs
URL="${URL:?"\$URL not set"}"
TOKEN="${TOKEN:?"\$TOKEN not set"}"
REASON="${REASON:?"\$REASON not set"}"

curl \
  -X PUT \
  "${URL}/no" \
  -d "token=${TOKEN}" \
  -d "reason=${REASON}" \
  -d "buildnumber=0"

