#!/bin/bash

set -eux

declare -a stale_branches=()
pushd repo > /dev/null
  branches=$(git branch -r | grep -v -- "->" )
  for branch in ${branches}; do
    if [[ -z  $(git log -1 --since='1 month ago' -s "$branch") ]]; then
      stale_branches+=("$branch")
    fi
  done
popd

if [[ ${#stale_branches[@]} -ne 0 ]]; then
  echo "The following branches have not been updated in the last month:"
  echo "${stale_branches[@]}"
  exit 1
fi


