#!/bin/bash
set -xeu

export CONFIG="$PWD/integration-config/${CONFIG_FILE_PATH}"
export GOPATH=$GOPATH:$PWD/routing-release

pushd routing-release/src/code.cloudfoundry.org/routing-acceptance-tests
  for i in ${PACKAGES}
  do
    ginkgo -r \
      -slowSpecThreshold=120 \
      -keepGoing \
      -randomizeAllSpecs \
      -skipPackage=helpers \
      -nodes="${NODES}" \
      "$i"
  done
popd
