#!/bin/bash -exu

source runtime-ci/tasks/shared-functions

function create_message_file() {
  local BOSH_LOGS_LINK=""
  if [[ -e "$BOSH_LOGS_PREFIX/$(basename bosh-logs/cf-*.tgz)" ]]; then
    BOSH_LOGS_LINK="$BOSH_LOGS_PREFIX/$(basename bosh-logs/cf-*.tgz)" 
  fi
  cat > slack-message/message.txt <<EOF
cf-deployment: $RELEASE_NAME/$RELEASE_VERSION> failed. Please review the details and reach out to Rel-Int(<#$RELINT_SLACK_CHANNEL|release-integration>) for any questions.

https://github.com/cloudfoundry/cf-deployment/tree/$(branch_name $RELEASE_NAME $RELEASE_VERSION)

$BOSH_LOGS_LINK
EOF
}

function main() {
  local RELEASE_VERSION="$(cat release/version)"
  local BRANCH_NAME="$(branch_name $RELEASE_NAME $RELEASE_VERSION)"

  export GOPATH="$PWD/go"
  export PATH=$GOPATH/bin:$PATH

  local cwd=$PWD

  pushd runtime-ci/tasks/create-slack-message/
    go run get-slack-channel.go \
      -cf-teams=$cwd/relint-team/team/cf-teams.yml \
      -repository $REPOSITORY \
      > $cwd/slack-message/channel.txt
    local error_code=$?
    if [[ "$error_code" != 0 ]]; then
      echo "Failed to get slack channel for $REPOSITORY"
      exit $error_code
    fi
  popd

  create_message_file
}

main "$@"
