---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
- name: bosh-logs
  optional: true
- name: release
- name: runtime-ci

outputs:
- name: slack-message

run:
  path: runtime-ci/tasks/create-slack-message/task

params:
  BOSH_LOGS_PREFIX:
  RELEASE_NAME:
  RELINT_SLACK_CHANNEL: C0FAEKGUQ
