#!/bin/bash -eu

# shellcheck disable=SC1091
source runtime-ci/tasks/shared-functions

function create_message_file() {
  local release_version
  release_version="$1"

  local release_branch
  release_branch="$2"

  local bosh_logs_link=""
  if [[ -e "bosh-logs/$(basename bosh-logs/cf-*.tgz)" ]]; then
    bosh_logs_link="${BOSH_LOGS_PREFIX}/$(basename bosh-logs/cf-*.tgz)"
  else
    bosh_logs_link="unavailable"
  fi

  cat > slack-message/message.txt <<EOF
cf-deployment: ${RELEASE_NAME}/${release_version} failed. Please review the details and reach out in <#${RELINT_SLACK_CHANNEL}|wg-app-runtime-deployments> with any questions.

Branch containing changes: https://github.com/cloudfoundry/cf-deployment/tree/${release_branch}

BOSH logs: ${bosh_logs_link}
EOF
}

function main() {
  local release_version
  release_version="$(cat release/version)"

  local release_branch
  release_branch="$(branch_name "${RELEASE_NAME}" "${release_version}")"

  create_message_file "${release_version}" "${release_branch}"
}

main "$@"
