---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: runtime-ci
- name: relint-team

run:
  path: runtime-ci/tasks/create-slack-message/task

params:
  RELEASE_NAME:
