#!/bin/bash

set -eux

has_no_commits_in_last_month () {
  [[ -z $(git log -1 --since='1 month ago' -s "$1") ]]
}

fetch_all_branches () {
  sed -i -e 's/develop/*/g' .git/config
  git fetch --all
}

declare -a stale_branches=()
pushd repo > /dev/null
  fetch_all_branches
  branches=$(git branch -r | grep -v -- "->" )
  for branch in ${branches}; do
    if has_no_commits_in_last_month "$branch"; then
      stale_branches+=("$branch")
    fi
  done
popd

num_stale_branches=${#stale_branches[@]}
if [[ $num_stale_branches -ne 0 ]]; then
  echo "The following branches have not been updated in the last month:"
  echo "${stale_branches[@]}"
  exit 1
fi

