---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/relint-base

inputs:
- name: runtime-ci
- name: repo

run:
  path: runtime-ci/tasks/validate-branch-freshness/task

params:
  MONTHS: 2
  DELETE_STALE_BRANCHES: false
  DEPLOY_KEY:
