#!/bin/bash
set -exu

root_dir="${PWD}"

# Inputs
export BOSH_USER
export BOSH_PASSWORD
BOSH_TARGET=$(cat "${root_dir}/target-file-dir/${BOSH_TARGET_FILE:?"Path to BOSH_TARGET_FILE must be provided"}")
ERRAND_NAME="${ERRAND_NAME:?"ERRAND_NAME must be provided"}"
BOSH_CA_CERT="ca-cert/${CA_CERT_FILE:?"CA_CERT_FILE must be provided"}"
DEPLOYMENT_NAME="${DEPLOYMENT_NAME:?"DEPLOYMENT_NAME must be provided"}"
BOSH_USER=$(cat "${BOSH_USER_FILE:?"Path to BOSH_USER_FILE must be provided"}")

set +x
echo "Using password from ${BOSH_PASSWORD_FILE:?"Path to BOSH_PASSWORD_FILE must be provided"}"
echo 'export BOSH_PASSWORD="REDACTED"'
BOSH_PASSWORD=$(cat "${BOSH_PASSWORD_FILE}")

set -x

bosh \
  -n \
  -e "${BOSH_TARGET}" \
  --ca-cert="${BOSH_CA_CERT}" \
  -d "${DEPLOYMENT_NAME}" \
  run-errand "$ERRAND_NAME" \
  --keep-alive \
  --download-logs \
  --logs-dir logs-dir
