#!/bin/sh
set -eux

echo "Finding cf-final-release-election issue url"
set +x
  issue_url=$(curl -s -f "https://api.github.com/repos/cloudfoundry/cf-final-release-election/issues?access_token=${GH_ACCESS_TOKEN}" \
    | jq -r .[0].html_url)
set -x

echo "Hey there <@dsabeti> <@staylor>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/release-integration
echo "Hey there <@efarrar> <@genevieve>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/infrastructure
echo "Hey there <@valepert> <@smoser>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/postgres-release
echo "Hey there <@shannon> <@ahurley>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/routing
echo "Hey there <@stummidi> <@jhamon>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/uaa
echo "Hey there <@hev> <@josmith>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/loggregator
echo "Hey there <@zach> <@gerg>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/capi
echo "Hey there <@slevine> <@scoward>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/buildpacks
echo "Hey there <@emalm> <@jvshahid>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/diego
echo "Hey there <@uramachandran> <@achin>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/container-networking
echo "Hey there <@nebhale>. Could you please take a look at the latest release candidate: ${issue_url} cc <@dsabeti>" > slack-messages/java-buildpack

echo "Successfully saved a Slack messages"

