#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

validate_variables() {
  RELEASE_NAME="${RELEASE_NAME:?"RELEASE_NAME must be provided"}"
}

MANIFEST_PATH=manifest/${MANIFEST_FILENAME}

deploy_for_compilation() {
  cat << EOF > compilation-manifest.yml
---
instance_groups: []
name: cf-compilation-${RELEASE_NAME}
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1
  update_watch_time: 1
releases:
- name: "$(   bosh interpolate ${MANIFEST_PATH} --path /releases/name=${RELEASE_NAME}/name)"
  sha1: "$(   bosh interpolate ${MANIFEST_PATH} --path /releases/name=${RELEASE_NAME}/sha1)"
  url:  "$(   bosh interpolate ${MANIFEST_PATH} --path /releases/name=${RELEASE_NAME}/url)"
  version: "$(bosh interpolate ${MANIFEST_PATH} --path /releases/name=${RELEASE_NAME}/version)"
stemcells:
$(bosh interpolate ${MANIFEST_PATH} --path /stemcells)

EOF

  bosh \
    -n \
    -d cf-compilation-${RELEASE_NAME} \
    deploy compilation-manifest.yml
}

export_release() {
  local stemcell_os_version
  stemcell_os_version=$(bosh interpolate ${MANIFEST_PATH} --path "/stemcells/os=${STEMCELL_OS}/version")
  local bosh_release_version
  bosh_release_version=$(bosh interpolate ${MANIFEST_PATH} --path "/releases/name=${RELEASE_NAME}/version")
  pushd exported-release
  bosh export-release -d "cf-compilation-${RELEASE_NAME}" "${RELEASE_NAME}/${bosh_release_version}" "${STEMCELL_OS}/${stemcell_os_version}"
  popd
}

delete_deployment() {
  bosh deld -n -d cf-compilation-${RELEASE_NAME}
}

main() {
  validate_variables
  setup_bosh_env_vars

  deploy_for_compilation

  export_release

  delete_deployment
}

main
