#!/bin/bash

set -eu

root_dir="${PWD}"

# Inputs
RUNTIME_CI_DIR="${root_dir}/${RUNTIME_CI_DIR:?"\$RUNTIME_CI_DIR must be provided"}"

function verify_image {
  set +e
  if ! grep "repository: relintdockerhubpushbot/$(basename "${1}")" task.yml >/dev/null; then
    echo "${1}/task.yml"
    grep 'image:' task.yml
  fi
  set -e
}

errors_file=$(mktemp /tmp/errors.XXXXX)
pushd "${RUNTIME_CI_DIR}/scripts/ci" >/dev/null
  find . -type d ! -path . | while read -r dir; do
    pushd "${dir}" >/dev/null
      verify_image "${dir}" >> "${errors_file}"
    popd >/dev/null; done
popd >/dev/null

if [ -s "${errors_file}" ]; then
  echo "The following tasks are not using the correct docker image:"
  cat "${errors_file}"
  exit 1
fi

echo "All tasks use the correct docker image"
