#!/bin/bash
set -exu

root_dir="${PWD}"

# Inputs
DIEGO_RELEASE_DIR="${root_dir}/${DIEGO_RELEASE_DIR:?"\$DIEGO_RELEASE_DIR not set"}"

CF_MANIFEST_PATH="${root_dir}/cf-manifest/${CF_MANIFEST_PATH:?"\$CF_MANIFEST_PATH not set"}"
PROPERTY_OVERRIDES_PATH="${root_dir}/property-overrides/${PROPERTY_OVERRIDES_PATH:?"\$PROPERTY_OVERRIDES_PATH not set"}"
INSTANCE_COUNT_OVERRIDES_PATH="${root_dir}/instance-count-overrides/${INSTANCE_COUNT_OVERRIDES_PATH:?"\$INSTANCE_COUNT_OVERRIDES_PATH not set"}"
RELEASE_VERSIONS_PATH="${root_dir}/release-versions/${RELEASE_VERSIONS_PATH:?"\$RELEASE_VERSIONS_PATH not set"}"
IAAS_SETTINGS_PATH="${root_dir}/iaas-settings/${IAAS_SETTINGS_PATH:?"\$IAAS_SETTINGS_PATH not set"}"
if  [ "${USE_MYSQL}" == "true" ]; then
  DIEGO_MYSQL_OVERRIDES_PATH="${root_dir}/diego-mysql-overrides/${DIEGO_MYSQL_OVERRIDES_PATH:?"\$DIEGO_MYSQL_OVERRIDES_PATH not set"}"
fi

# Outputs
GENERATED_DIEGO_MANIFEST_DIR="${root_dir}/${GENERATED_DIEGO_MANIFEST_DIR:?"\$GENERATED_DIEGO_MANIFEST_DIR not set"}"
USE_GARDEN_RUNC=false

pushd "${DIEGO_RELEASE_DIR}"
  ./scripts/generate-deployment-manifest \
    -c "${CF_MANIFEST_PATH}" \
    -i "${IAAS_SETTINGS_PATH}" \
    -p "${PROPERTY_OVERRIDES_PATH}" \
    -n "${INSTANCE_COUNT_OVERRIDES_PATH}" \
    $([ "${NETMAN_OVERRIDES_PATH}" != "" ] && echo "-N ${root_dir}/${NETMAN_OVERRIDES_PATH}") \
    -v "${RELEASE_VERSIONS_PATH}" \
    -g \
    $([ "${USE_ETCD}" == "false" ] && echo "-x") \
    $([ "${USE_MYSQL}" == "true" ] && echo "-s ${DIEGO_MYSQL_OVERRIDES_PATH}") \
    > "${GENERATED_DIEGO_MANIFEST_DIR}/diego-deployment.yml"
popd
