#!/bin/bash
set -exu

root_dir="${PWD}"

# Inputs
set +x
BOSH_PASSWORD="${BOSH_PASSWORD:?"\$BOSH_PASSWORD not set"}"
set -x
DIEGO_RELEASE_DIR="${root_dir}/${DIEGO_RELEASE_DIR:?"\$DIEGO_RELEASE_DIR not set"}"
BOSH_USER="${BOSH_USER:?"\$BOSH_USER not set"}"
BOSH_TARGET="${BOSH_TARGET:?"\$BOSH_TARGET not set"}"

CF_MANIFEST=${root_dir}/${CF_MANIFEST:?"\$CF_MANIFEST not set"}
PROPERTY_OVERRIDES="${root_dir}/${PROPERTY_OVERRIDES:?"\$PROPERTY_OVERRIDES not set"}"
INSTANCE_COUNT_OVERRIDES="${root_dir}/${INSTANCE_COUNT_OVERRIDES:?"\$INSTANCE_COUNT_OVERRIDES not set"}"
RELEASE_VERSIONS="${root_dir}/${RELEASE_VERSIONS:?"\$RELEASE_VERSIONS not set"}"
IAAS_SETTINGS="${root_dir}/${IAAS_SETTINGS:?"\$IAAS_SETTINGS not set"}"

# Outputs
GENERATED_DIEGO_MANIFEST_DIR="${root_dir}/${GENERATED_DIEGO_MANIFEST_DIR:?"\$GENERATED_DIEGO_MANIFEST_DIR not set"}"

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
scripts_dir="$(cd "${my_dir}/.." && pwd)"

"${scripts_dir}/bosh_setup"

pushd "${DIEGO_RELEASE_DIR}"
  ./scripts/generate-deployment-manifest \
    -c "${CF_MANIFEST}" \
    -i "${IAAS_SETTINGS}" \
    -p "${PROPERTY_OVERRIDES}" \
    -n "${INSTANCE_COUNT_OVERRIDES}" \
    -v "${RELEASE_VERSIONS}" \
    > "${GENERATED_DIEGO_MANIFEST_DIR}/diego-deployment.yml"
popd
