#!/bin/bash
set -exu

root_dir="${PWD}"

# Inputs
DIEGO_RELEASE_DIR="${root_dir}/${DIEGO_RELEASE_DIR:?"\$DIEGO_RELEASE_DIR not set"}"

CF_MANIFEST_PATH="${root_dir}/cf-manifest/${CF_MANIFEST_PATH:?"\$CF_MANIFEST_PATH not set"}"
PROPERTY_OVERRIDES_PATH="${root_dir}/property-overrides/${PROPERTY_OVERRIDES_PATH:?"\$PROPERTY_OVERRIDES_PATH not set"}"
INSTANCE_COUNT_OVERRIDES_PATH="${root_dir}/instance-count-overrides/${INSTANCE_COUNT_OVERRIDES_PATH:?"\$INSTANCE_COUNT_OVERRIDES_PATH not set"}"
RELEASE_VERSIONS_PATH="${root_dir}/release-versions/${RELEASE_VERSIONS_PATH:?"\$RELEASE_VERSIONS_PATH not set"}"
IAAS_SETTINGS_PATH="${root_dir}/iaas-settings/${IAAS_SETTINGS_PATH:?"\$IAAS_SETTINGS_PATH not set"}"
VSPHERE="${VSPHERE}"

# Outputs
GENERATED_DIEGO_MANIFEST_DIR="${root_dir}/${GENERATED_DIEGO_MANIFEST_DIR:?"\$GENERATED_DIEGO_MANIFEST_DIR not set"}"
USE_GARDEN_RUNC=false


if [ "$VSPHERE" == "false" ]; then
  USE_GARDEN_RUNC=true
fi

if [ "$USE_MYSQL" == "true" ]; then
  cat << EOF > /tmp/mysql-stubs.yml
sql_overrides:
  bbs:
    db_connection_string: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}
    db_driver: mysql
    max_open_connections: 500
EOF
fi

pushd "${DIEGO_RELEASE_DIR}"
  ./scripts/generate-deployment-manifest \
    -c "${CF_MANIFEST_PATH}" \
    -i "${IAAS_SETTINGS_PATH}" \
    -p "${PROPERTY_OVERRIDES_PATH}" \
    -n "${INSTANCE_COUNT_OVERRIDES_PATH}" \
    -v "${RELEASE_VERSIONS_PATH}" \
    $([ "${USE_GARDEN_RUNC}" == "true" ] && echo "-g") \
    $([ "${USE_ETCD}" == "false" ] && echo "-x") \
    $([ "${USE_MYSQL}" == "true" ] && echo "-s /tmp/mysql-stubs.yml") \
    > "${GENERATED_DIEGO_MANIFEST_DIR}/diego-deployment.yml"
popd
