#!/bin/bash

set -xeu
DIR="$(pwd)"

function commit_bbl_state_file {
  pushd "${DIR}/env-repo"
    if [[ -n $(git status --porcelain) ]]; then
      git config user.name "CF MEGA BOT"
      git config user.email "cf-mega@pivotal.io"
      git add bbl-infrastructure
      git commit -m "Update bbl artifacts"
    fi
  popd

  pushd "${DIR}"
    shopt -s dotglob
    cp -R env-repo/* updated-env-repo/
  popd
}

trap commit_bbl_state_file EXIT

pushd env-repo
  set +x
  echo "bbl \
    --state-dir bbl-infrastructure \
    --aws-access-key-id [REDACTED] \
    --aws-secret-access-key [REDACTED] \
    --aws-region us-east-1 \
    up"
  bbl \
    --state-dir bbl-infrastructure \
    --aws-access-key-id "$AWS_ACCESS_KEY_ID" \
    --aws-secret-access-key "$AWS_SECRET_ACCESS_KEY" \
    --aws-region us-east-1 \
    up

  echo "$BBL_LB_CERT" > /tmp/bbl-cert
  echo "$BBL_LB_KEY" > /tmp/bbl-key
  set -x

  # The two commands below amount to "create or update"
  bbl \
    --state-dir bbl-infrastructure \
    create-lbs \
    --type=cf \
    --cert=/tmp/bbl-cert \
    --key=/tmp/bbl-key \
    --skip-if-exists

  bbl \
    --state-dir bbl-infrastructure \
    update-lbs \
    --cert=/tmp/bbl-cert \
    --key=/tmp/bbl-key
popd
