#!/bin/bash -exu

update_windows_cell() {
  local windows_cell_version
  windows_cell_version=$(cat windows-stemcell/version)

  update_windows_cell_ops_file=$(mktemp)
(
cat << EOF
---
- type: replace
  path: /path=~1stemcells~1-
  value:
    type: replace
    path: /stemcells/-
    value:
      alias: windows
      os: windows2012R2
      version: "${windows_cell_version}"
EOF
) > "${update_windows_cell_ops_file}"

  bosh interpolate ops-files/operations/windows-cell.yml -o "${update_windows_cell_ops_file}" > updated-stemcell-ops-file/windows-cell.yml
}

output_commit_message() {
  current_stemcell_version=$(bosh interpolate ops-files/operations/windows-cell.yml --path=/path=~1stemcells~1-/value/version)
  if [ "${current_stemcell_version}" == "$(cat windows-stemcell/version)" ]; then
    echo "No windows stemcell update" > commit-message/${COMMIT_MESSAGE_PATH}
  else
    echo "Windows stemcell updated to $(cat windows-stemcell/version)" > commit-message/${COMMIT_MESSAGE_PATH}
  fi
}

main() {
  update_windows_cell
  output_commit_message
}

main
