#!/bin/bash -exu

pushd google-creds-dir > /dev/null
  for i in $(seq 1 $TIMEOUT); do
    gcloud auth activate-service-account --key-file=google_account_creds.json
    healthy_backends="$(gcloud compute backend-services get-health ${GCP_BACKEND_SERVICE} --global --project=${GCP_PROJECT_ID} | grep "healthState: HEALTHY" | wc -l |  tr -d '[:space:]')"
    if [ "${healthy_backends}" -eq "2" ]; then
      exit 0
    fi
    sleep 1
  done
popd > /dev/null

echo "timeout exceeded"
exit 1