#!/bin/bash
set -exu

root_dir="${PWD}"


fail_fast() {
if [ ! -f semantic-version/version ]; then
  exit 1
fi
}

setup_aws_access() {
  set +x
  BLOBS_BUCKET_ACCESS_KEY_ID="${BLOBS_BUCKET_ACCESS_KEY_ID:?"\$BLOBS_BUCKET_ACCESS_KEY_ID not set"}"
  BLOBS_BUCKET_SECRET_KEY="${BLOBS_BUCKET_SECRET_KEY:?"\$BLOBS_BUCKET_SECRET_KEY not set"}"
  set -x
}

write_config_private() {
  set +x
cat > "release-repo/config/private.yml" <<EOF
---
blobstore:
  provider: s3
  options:
    access_key_id: ${BLOBS_BUCKET_ACCESS_KEY_ID}
    secret_access_key: ${BLOBS_BUCKET_SECRET_KEY}
EOF
  set -x
}

create_release() {
  local sem_ver=$(cat semantic-version/version)
  pushd release-repo > /dev/null
    git config user.name "CF MEGA BOT"
    git config user.email "cf-mega@pivotal.io"

    bosh -n create-release --final --version=$sem_ver

    git add .final_builds releases

    git commit -m "Final release, version $sem_ver."
  popd > /dev/null
}

main() {
  fail_fast

  setup_aws_access

  write_config_private

  create_release

  git clone release-repo final-release-repo
}

main
