#!/bin/bash -eu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/shared-functions

function main() {
  local new_version
  new_version="$(cat version/version)"

  pushd cf-deployment-concourse-tasks
    local old_version
    old_version="$(bosh int bbl-up/task.yml --path /image_resource/source/tag)"

    perl -pi -e "s/${old_version}/v${new_version}/g" ./*/task.yml
    git add ./*/task.yml
    commit_with_message "${PWD}" <(echo "Update docker image to ${new_version}")
  popd
}

main
