#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/cf-deployment-concourse-tasks/shared-functions

function create_compilation_opsfile() {
  cat << EOF > compilation.yml
---
- type: replace
  path: /name
  value: cf-compilation-${RELEASE_NAME}

- type: replace
  path: /instance_groups
  value: []

EOF
}

function main() {
  setup_bosh_env_vars
  create_compilation_opsfile
  vars_store="$(mktemp)"

  bosh \
    -n \
    -d cf-compilation-${RELEASE_NAME} \
    deploy cf-deployment/cf-deployment.yml \
    -o compilation.yml
}

main
