#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

root_dir="${PWD}"

# Outputs
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?"\$OUTPUT_DIR not set"}"

SET_DEPLOYMENT_YML=""
if [ -n "${DEPLOYMENT_YML}" ]; then
  SET_DEPLOYMENT_YML="-d \"${DEPLOYMENT_YML}\""
fi

bosh \
  -n \
  --color\
  -t "${BOSH_DIRECTOR}" \
  ${SET_DEPLOYMENT_YML} \
  $COMMAND
