#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

root_dir="${PWD}"

# Outputs
OUTPUT_DIR="${root_dir}/${OUTPUT_DIR:?"\$OUTPUT_DIR not set"}"

bosh \
  -n \
  --color\
  -t "${BOSH_DIRECTOR}" \
  -d "${DEPLOYMENT_YML}" \
  $COMMAND
