#!/bin/bash -exu

function create_latest_stemcell_opsfile() {
  cat << EOF > latest_stemcell.yml
---
- type: replace
  path: /name
  value: cf-dry-run

- type: replace
  path: /stemcells/alias=default/version
  value: latest
EOF
}

function main() {
  start-bosh
  source /tmp/local-bosh/director/env

  create_latest_stemcell_opsfile
  vars_store="$(mktemp)"

  # bosh -n upload-stemcell stemcell/*.tgz

  bosh \
    -n \
    -d cf-dry-run \
    interpolate cf-deployment/cf-deployment.yml \
    --vars-store "${vars_store}" \
    --var-errs \
    --var-errs-unused \
    -v system_domain="docker-cpi.cf-app.com" \
    -o latest_stemcell.yml \
    -o ops-files/operations/gcp.yml > /dev/null

  bosh \
    -n \
    -d cf-dry-run \
    deploy cf-deployment/cf-deployment.yml \
    --dry-run \
    --vars-store="${vars_store}" \
    -v system_domain="docker-cpi.cf-app.com" \
    -o latest_stemcell.yml
}

main
