#!/bin/bash

set -eu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

trap close_bbl_ssh_connection EXIT

pushd "bbl-state/${BBL_STATE_DIR}"
  eval "$(bbl print-env)"
  bosh -n update-cloud-config <(bosh int cloud-config/cloud-config.yml -o cloud-config/ops.yml --vars-file vars/cloud-config-vars.yml)
popd
