#!/bin/bash
set -eux

BOSH_TARGET=$(cat "target/${TARGET_FILE}")
BOSH_USER=$(cat username/"${USERNAME_FILE}")
BOSH_MANIFEST="manifest/${MANIFEST_FILE}"
set +x
BOSH_PASSWORD=$(cat "password/${PASSWORD_FILE}")

echo "bosh -n -t ${BOSH_TARGET} -u ${BOSH_USER} -p REDACTED -d ${BOSH_MANIFEST} deploy --redact-diff"
bosh \
  -n \
  -t "${BOSH_TARGET}" \
  -u "${BOSH_USER}" \
  -p "${BOSH_PASSWORD}" \
  -d "${BOSH_MANIFEST}" \
  deploy \
  --redact-diff
set -x
