#!/bin/bash
set -eux

BOSH_TARGET=$(cat "target/${TARGET_FILE}")
export BOSH_USER=$(cat username/"${USERNAME_FILE}")
BOSH_MANIFEST="manifest/${MANIFEST_FILE}"
set +x
export BOSH_PASSWORD=$(cat "password/${PASSWORD_FILE}")
BOSH_CA_CERT="ca-cert/${CA_CERT_FILE}"
DEPLOYMENT_NAME=$(grep -E "^name:" "$BOSH_MANIFEST" | awk '{print $2}')

ops_file_argument=""
deployment_var_file_argument=""

if [ "${OPS_FILE}" != "" ]; then
  ops_file_argument="-o manifest/${OPS_FILE}"
fi

if [ "${DEPLOYMENT_VAR_FILE}" != "" ]; then
  deployment_var_file_argument="-l manifest-properties/${DEPLOYMENT_VAR_FILE}"
fi

echo "bosh -n -d ${DEPLOYMENT_NAME} -e ${BOSH_TARGET} --ca-cert=${BOSH_CA_CERT} deploy ${deployment_var_file_argument} ${ops_file_argument} ${BOSH_MANIFEST}"
bosh \
  -n \
  -d "${DEPLOYMENT_NAME}" \
  -e "${BOSH_TARGET}" \
  --ca-cert="${BOSH_CA_CERT}" \
  deploy \
  $deployment_var_file_argument \
  $ops_file_argument \
  "${BOSH_MANIFEST}"

set -x
