---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/relint-base

inputs:
- name: runtime-ci

run:
  path: runtime-ci/tasks/create-cats-flake-story/task
