#!/bin/bash
set -eux

BOSH_TARGET=$(cat "target/${TARGET_FILE}")
BOSH_USER=$(cat username/"${USERNAME_FILE}")
set +x
BOSH_PASSWORD=$(cat "password/${PASSWORD_FILE}")


echo "bosh -n  -t ${BOSH_TARGET}  -u ${BOSH_USER}  -p REDACTED  upload stemcell  stemcell/$STEMCELL_NAME  --skip-if-exists"
bosh \
  -n \
  -t "${BOSH_TARGET}" \
  -u "${BOSH_USER}" \
  -p "${BOSH_PASSWORD}" \
  upload stemcell \
  stemcell/${STEMCELL_NAME}
set -x
