#!/bin/bash
set -eux

BOSH_IO_STEMCELL_URL="https://bosh.io/d/stemcells/"

BOSH_AGENT="go_agent"
OS=$(bosh interpolate --path=/stemcells/alias=default/os cf-deployment.yml)
VERSION=$(bosh interpolate --path=/stemcells/alias=default/version cf-deployment/cf-deployment.yml)

# Ask bosh if it already has our OS / version stemcell combination
EXISTING_STEMCELL=$(bosh stemcells | grep $OS | awk '{print $2}' | tr -d "\*" | grep ^"$VERSION"$ )

STEMCELL_NAME="bosh"

if [[ $INFRASTRUCTURE -eq "aws" ]]; then
  STEMCELL_NAME="$STEMCELL_NAME-aws-xen-hvm"
elif [[ $INFRASTRUCTURE -eq "google" ]]; then
  STEMCELL_NAME="$STEMCELL_NAME-google-kvm"
elif [[ $INFRASTRUCTURE -eq "boshlite" ]]; then
  STEMCELL_NAME="$STEMCELL_NAME-warden-boshlite"
fi

STEMCELL_NAME="$STEMCELL_NAME-$OS-$BOSH_AGENT"
BOSH_IO_STEMCELL_URL="$BOSH_IO_STEMCELL_URL/$STEMCELL_NAME?v=$VERSION"

# If bosh already has our stemcell, exit 0
if [ "$EXISTING_STEMCELL" ]; then
  echo "Task bosh-upload-stemcell:"
  echo "Stemcell '$STEMCELL_NAME/$VERSION' already exists.  Exiting..."
  exit 0
fi

# ... otherwise, begin the upload process
set +x
source env-repo/env/environment
set -x

set | grep BOSH | grep -v PASSWORD

set +x
bosh \
  -n \
  upload-stemcell \
  $BOSH_IO_STEMCELL_URL
set -x

