#!/bin/bash
set -eux

export BOSH_USER
export BOSH_PASSWORD
BOSH_USER=$(cat "username/${USERNAME_FILE}")
BOSH_TARGET=$(cat "target/${TARGET_FILE}")
BOSH_MANIFEST="manifest/${MANIFEST_FILE}"
BOSH_CA_CERT="ca-cert/${CA_CERT_FILE}"
DEPLOYMENT_NAME=$(grep -E "^name:" "$BOSH_MANIFEST" | awk '{print $2}')
RELEASE_NAME=$(grep final_name release/config/final.yml | awk '{print $2}')

set +u
DEPLOYMENT_VAR_FILE="manifest-properties/${DEPLOYMENT_VAR_FILE}"
OPS_FILE_DIR="ops-files/${OPS_FILE_DIR_PATH}"
set -u

set +x
echo "BOSH_PASSWORD=\$(cat password/${PASSWORD_FILE})"
BOSH_PASSWORD=$(cat "password/${PASSWORD_FILE}")
set -x

cat << EOF > ops.yml
---
- type: replace
  path: /releases/name=${RELEASE_NAME}
  value:
    name: ${RELEASE_NAME}
    version: create
    url: file://$(pwd)/release
EOF


VAR_FILES_FLAG=""
if [[ -f ${DEPLOYMENT_VAR_FILE} ]]; then
  VAR_FILES_FLAG="--var-files=${DEPLOYMENT_VAR_FILE}"
fi

OPS_FILE_FLAGS="-o ops.yml"
if [[ -d ${OPS_FILE_DIR} ]]; then
  for OPS_FILE in $OPS_FILE_DIR/*.yml; do
    OPS_FILE_FLAGS="$OPS_FILE_FLAGS -o $OPS_FILE"
  done
fi

bosh \
  -n \
  -d "${DEPLOYMENT_NAME}" \
  -e "${BOSH_TARGET}" \
  --ca-cert="${BOSH_CA_CERT}" \
  deploy \
  "${VAR_FILES_FLAG}" \
  "${OPS_FILE_FLAGS}" \
  "${BOSH_MANIFEST}"
