#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

root_dir="${PWD}"

# Inputs
set +x
BOSH_PASSWORD="${BOSH_PASSWORD:?"\$BOSH_PASSWORD not set"}"
set -x
DEPLOYMENTS_RUNTIME_DIR="${root_dir}/${DEPLOYMENTS_RUNTIME_DIR:?"\$DEPLOYMENTS_RUNTIME_DIR not set"}"
DIEGO_RELEASE_DIR="${root_dir}/${DIEGO_RELEASE_DIR:?"\$DIEGO_RELEASE_DIR not set"}"
ENVIRONMENT_NAME="${ENVIRONMENT_NAME:?"\$ENVIRONMENT_NAME not set"}"
BOSH_USER="${BOSH_USER:?"\$BOSH_USER not set"}"
BOSH_TARGET="${BOSH_TARGET:?"\$BOSH_TARGET not set"}"
INFRASTRUCTURE="${INFRASTRUCTURE:?"\$INFRASTRUCTURE not set"}"

# Outputs
GENERATED_DIEGO_MANIFEST_DIR="${root_dir}/${GENERATED_DIEGO_MANIFEST_DIR:?"\$GENERATED_DIEGO_MANIFEST_DIR not set"}"

environment_path="${DEPLOYMENTS_RUNTIME_DIR}/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

cf_deployment_name="cf-${ENVIRONMENT_NAME}"

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
scripts_dir="$(cd "${my_dir}/.." && pwd)"

"${scripts_dir}/bosh_setup"

pushd "${DIEGO_RELEASE_DIR}"
  bosh download manifest "${cf_deployment_name}" > /tmp/cf.yml
  spiff merge \
    "manifest-generation/misc-templates/${INFRASTRUCTURE}-iaas-settings.yml" \
    "${templates_path}/diego/iaas-settings-internal.yml" \
    "${stubs_path}/diego/iaas-settings.yml" \
    /tmp/cf.yml \
    > /tmp/iaas-settings.yml

  ./scripts/generate-deployment-manifest \
    -c /tmp/cf.yml \
    -i /tmp/iaas-settings.yml \
    -p "${stubs_path}/diego/property-overrides.yml" \
    -n "${stubs_path}/diego/instance-count-overrides.yml" \
    -k "${stubs_path}/diego/persistent-disk-overrides.yml" \
    -v "${stubs_path}/diego/release-versions.yml" \
    > ../generated-diego-manifest/diego-deployment.yml
popd
