#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

# Inputs
URL="${URL:?"\$URL not set"}"

set +x
TOKEN="${TOKEN:?"\$TOKEN not set"}"

cat <<EOF
curl \
  -X PUT \
  "${URL}/yes" \
  -d "token=[REDACTED]" \
  -d "buildnumber=0"
EOF

curl \
  -X PUT \
  "${URL}/yes" \
  -d "token=${TOKEN}" \
  -d "buildnumber=0"


