#!/usr/bin/env bash

set -euo pipefail

pushd "bbl-state/${BBL_STATE_DIR}"
  echo "Initializing Terraform..."
  pushd "./terraform"
    terraform init
  popd
  echo "Retrieving DB name from bbl outputs..."
  DB_NAME=$(bbl outputs | grep db_name | awk '{print $2}')
popd

echo "Generating external DB terraform vars file..."
cat <<EOT > vars-file/db.tfvars
cf_db_name = "${DB_NAME}"
project = "${GCP_PROJECT_ID}"
region = "${GCP_REGION}"
service_account_key = <<EOF
$(echo ${GCP_SERVICE_ACCOUNT_JSON} | jq . | sed 's/\n/\\n/g')
EOF
EOT
