---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: 'v15.0.0'

inputs:
- name: runtime-ci
- name: bbl-state

outputs:
- name: vars-file

params:
  BBL_STATE_DIR: bbl-state
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_JSON:
  VARS_DIR: bbl-state

run:
  path: runtime-ci/tasks/generate-external-db-vars-file/task
