#!/bin/bash -exu

function main() {
  local root_dir
  root_dir="${1}"

  export GOPATH="${root_dir}/go"
  export PATH=$GOPATH/bin:$PATH

  ln -s release "${RELEASE_NAME}-release"

  if [ -d compiled-release-tarball ]; then
    ln -s compiled-release-tarball "${RELEASE_NAME}-compiled-release-tarball"
  fi

  if [ -d current-commit-message ]; then
    cp current-commit-message/${COMMIT_MESSAGE_PATH} commit-message/${COMMIT_MESSAGE_PATH}
  fi

  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"
  ln -s "${root_dir}/runtime-ci" "${GOPATH}/src/github.com/cloudfoundry/runtime-ci"

  go get github.com/onsi/ginkgo/...

  pushd "${GOPATH}/src/github.com/cloudfoundry/runtime-ci/util/update-manifest-releases"
    ginkgo -r -randomizeSuites -randomizeAllSpecs .

    go run main.go --build-dir "${root_dir}" --release "${RELEASE_NAME}" --target "${TARGET}"
  popd
}

main "${PWD}"
