#!/bin/bash
set -exu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function bosh_delete_loggregator() {
  bosh -n delete-release loggregator
}

function main() {
  setup_bosh_env_vars
  bosh_delete_loggregator
}

trap close_bbl_ssh_connection EXIT

main
