#!/bin/bash -exu

function setup_bosh_env_vars() {
  set +x
  pushd env_repo
    BOSH_CA_CERT="$(bbl director-ca-cert)"
    export BOSH_CA_CERT
    BOSH_ENVIRONMENT=$(bbl director-address)
    export BOSH_ENVIRONMENT
    BOSH_CLIENT=$(bbl director-username)
    export BOSH_CLIENT
    BOSH_CLIENT_SECRET=$(bbl director-password)
    export BOSH_CLIENT_SECRET
  popd
  set -x
}

function download_legacy_manifests() {
  bosh download-manifest -d cf > cf.yml
  bosh download-manifest -d cf-diego > diego.yml
}

function extract_vars() {
  ../cf-deployment/transition/transition.sh \
  -cf cf.yml \
  -d diego.yml \
  -ca transition/ca-keys-stub.yml
}

function commit_vars_store_and_move_to_output() {
  pushd env_repo
    if [[ -n $(git status --porcelain) ]]; then
      git config user.name "CI Bot"
      git config user.email "cf-release-integration@pivotal.io"
      git add deployment-vars.yml
      git commit -m "Update vars-store after extraction from legacy manifests"
    fi
  popd

  git clone env_repo env_repo_with_vars_store
}

function main() {
  setup_bosh_env_vars

  pushd env_repo
  download_legacy_manifests
  extract_vars
  popd

  commit_vars_store_and_move_to_output
}

main
