#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

trap close_bbl_ssh_connection EXIT

function download_legacy_manifests() {
  pushd vars-store
    bosh manifest -d cf > cf.yml
    bosh manifest -d cf-diego > diego.yml
  popd
}

function extract_vars() {
  pushd vars-store
    ../cf-deployment-transition/extract-vars-store-from-manifests.sh \
    -cf cf.yml \
    -d diego.yml \
    $([ "${EXTRACT_CF_NETWORKING}" == "true" ] && echo "-N") \
    $([ "${EXTRACT_ROUTING}" == "true" ] && echo "-r") \
    $([ "${EXTRACT_LOCKET}" == "true" ] && echo "-Q") \
    -ca transition/ca-keys-stub.yml
  popd
}

function commit_vars_store_and_move_to_output() {
  pushd vars-store
    if [[ -n $(git status --porcelain) ]]; then
      git config user.name "CI Bot"
      git config user.email "cf-release-integration@pivotal.io"
      git add deployment-vars.yml
      git commit --allow-empty \
      -m "Update vars-store after extraction from legacy manifests"
    fi
  popd

  git clone vars-store extracted-vars-store
}

function main() {
  setup_bosh_env_vars

  download_legacy_manifests
  extract_vars

  commit_vars_store_and_move_to_output
}

main
