#!/bin/bash -exu

function setup_bosh_env_vars() {
  set +x
  pushd bbl-state
    BOSH_CA_CERT="$(bbl director-ca-cert)"
    export BOSH_CA_CERT
    BOSH_ENVIRONMENT=$(bbl director-address)
    export BOSH_ENVIRONMENT
    BOSH_CLIENT=$(bbl director-username)
    export BOSH_CLIENT
    BOSH_CLIENT_SECRET=$(bbl director-password)
    export BOSH_CLIENT_SECRET
  popd
  set -x
}

function download_legacy_manifests() {
  pushd vars-store
    bosh download-manifest -d cf > cf.yml
    bosh download-manifest -d cf-diego > diego.yml
  popd
}

function extract_vars() {
  pushd vars-store
    ../cf-deployment/transition/transition.sh \
    -cf cf.yml \
    -d diego.yml \
    -ca transition/ca-keys-stub.yml
  popd
}

function commit_vars_store_and_move_to_output() {
  pushd vars-store
    if [[ -n $(git status --porcelain) ]]; then
      git config user.name "CI Bot"
      git config user.email "cf-release-integration@pivotal.io"
      git add deployment-vars.yml
      git commit -m "Update vars-store after extraction from legacy manifests"
    fi
  popd

  git clone vars-store updated_vars_store
}

function main() {
  setup_bosh_env_vars

  download_legacy_manifests
  extract_vars

  commit_vars_store_and_move_to_output
}

main
