groups:
- name: cf-deployment-concourse-tasks
  jobs:
  - release-notes-template
  - ship-it-minor-cf-d-ct
  - ship-it-major-cf-d-ct
- name: runtime-ci-common-images
  jobs:
  - build-relint-base-docker-image
  - build-bosh-cli-docker-image
- name: private-cats-image
  jobs:
  - build-relint-private-docker-image
- name: stemcell-version-bump-resource-image
  jobs:
  - build-stemcell-version-bump-resource-docker-image

resources:
- name: runtime-ci
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: weekly
  type: time
  icon: clock-outline
  source:
    start: 7:00 -0700
    stop: 7:30 -0700
    interval: 168h

- name: cf-deployment-concourse-tasks
  type: git
  icon: github-box
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-deployment-concourse-tasks.git
    private_key: ((cfdct_readwrite_deploy_key.private_key))

- name: cf-deployment-concourse-tasks-latest-release
  type: git
  icon: github-box
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-deployment-concourse-tasks.git
    private_key: ((cfdct_readwrite_deploy_key.private_key))
    tag_filter: '*'

- name: runtime-ci-relint-base
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
    paths: [dockerfiles/relint-base/Dockerfile]

- name: runtime-ci-bosh-cli
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
    paths: [dockerfiles/bosh-cli/Dockerfile]

- name: runtime-ci-stemcell-version-bump-resource
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
    paths:
    - ci/resources/stemcell-version-bump/**

- name: bosh-cli-github-release
  type: github-release
  icon: github-face
  source:
    user: cloudfoundry
    repository: bosh-cli
    access_token: ((release_integration_download_bot_access_token))

- name: terraform-github-release
  type: github-release
  icon: github-face
  source:
    user: hashicorp
    repository: terraform
    access_token: ((release_integration_download_bot_access_token))

- name: bbl-github-release
  type: github-release
  icon: github-face
  source:
    user: cloudfoundry
    repository: bosh-bootloader
    access_token: ((release_integration_download_bot_access_token))

- name: cf-deployment-concourse-tasks-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/cf-relint-ci-semver.git
    branch: master
    private_key: ((cf_relint_ci_semver_readwrite_deploy_key.private_key))
    git_user: "CF RELINT BOT <cf-release-integration@pivotal.io>"
    file: cf-deployment-concourse-tasks-version

- name: relint-base-image
  type: docker-image
  icon: docker
  source:
    repository: relintdockerhubpushbot/relint-base
    username: ((dockerhub.username))
    password: ((dockerhub.password))
    email: cf-release-integration+dockerhub-push-bot@pivotal.io

- name: bosh-cli-image
  type: docker-image
  icon: docker
  source:
    repository: relintdockerhubpushbot/bosh-cli
    username: ((dockerhub.username))
    password: ((dockerhub.password))
    email: cf-release-integration+dockerhub-push-bot@pivotal.io


- name: diego-docker-app-custom
  type: docker-image
  icon: docker
  source:
    repository: cloudfoundry/diego-docker-app-custom

- name: relint-private-cats-image
  type: docker-image
  icon: docker
  source:
    repository: relintprivateregistry/privatecats
    username: ((private_dockerhub.username))
    password: ((private_dockerhub.password))
    email: cf-release-integration+private-registry@pivotal.io

- name: stemcell-version-bump-resource-image
  type: docker-image
  icon: docker
  source:
    repository: relintdockerhubpushbot/stemcell-version-bump-resource
    username: ((dockerhub.username))
    password: ((dockerhub.password))
    email: cf-release-integration+dockerhub-push-bot@pivotal.io

jobs:
- name: release-notes-template
  public: true
  plan:
  - in_parallel:
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks
      trigger: true
    - get: cf-deployment-concourse-tasks-latest-release
  - task: generate-release-notes-template
    file: runtime-ci/tasks/cf-decota-release-notes-template/task.yml

- name: ship-it-minor-cf-d-ct
  public: true
  plan:
  - in_parallel:
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks-version
      params: {bump: minor}
    - get: cf-deployment-concourse-tasks
  - put: cf-deployment-concourse-tasks
    params:
      repository: cf-deployment-concourse-tasks
      tag: cf-deployment-concourse-tasks-version/version
      tag_prefix: v
  - put: cf-deployment-concourse-tasks-version
    params: {bump: minor}

- name: ship-it-major-cf-d-ct
  public: true
  plan:
  - in_parallel:
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks-version
      params: {bump: major}
    - get: cf-deployment-concourse-tasks
  - put: cf-deployment-concourse-tasks
    params:
      repository: cf-deployment-concourse-tasks
      tag: cf-deployment-concourse-tasks-version/version
      tag_prefix: v
  - put: cf-deployment-concourse-tasks-version
    params: {bump: major}

- name: build-relint-base-docker-image
  public: true
  plan:
  - timeout: 4h
    do:
    - in_parallel:
      - get: weekly
        trigger: true
      - get: runtime-ci-relint-base
        trigger: true
    - put: relint-base-image
      params:
        build: runtime-ci-relint-base/dockerfiles/relint-base/
        push: true

- name: build-bosh-cli-docker-image
  public: true
  plan:
  - timeout: 4h
    do:
    - in_parallel:
      - get: weekly
        trigger: true
      - get: runtime-ci
      - get: runtime-ci-bosh-cli
        trigger: true
      - get: relint-base-image
        trigger: true
        passed: [build-relint-base-docker-image]
      - get: bosh-cli-github-release
        trigger: true
      - get: bbl-github-release
        trigger: true
      - get: terraform-github-release
        trigger: true
    - task: create-bosh-cli-json
      file: runtime-ci/tasks/create-version-json/task.yml
      input_mapping:
        version: bosh-cli-github-release
        # This is an example of that chaining we spoke of earlier
        input-version-json: bosh-cli-github-release
      params:
        key: bosh_cli_version
    - task: create-bbl-json
      file: runtime-ci/tasks/create-version-json/task.yml
      input_mapping:
        version: bbl-github-release
        # This is an example of that chaining we spoke of earlier
        input-version-json: version-json
      params:
        key: bbl_version
    - task: create-terraform-json
      file: runtime-ci/tasks/create-version-json/task.yml
      input_mapping:
        version: terraform-github-release
        # This is an example of that chaining we spoke of earlier
        input-version-json: version-json
      params:
        key: terraform_version
    - put: bosh-cli-image
      params:
        build: runtime-ci-bosh-cli/dockerfiles/bosh-cli/
        push: true
        build_args_file: version-json/version.json

- name: build-relint-private-docker-image
  public: true
  plan:
  - timeout: 4h
    do:
    - get: diego-docker-app-custom
      trigger: true
      params:
        save: true
    - put: relint-private-cats-image
      params:
        load: diego-docker-app-custom
        push: true

- name: build-stemcell-version-bump-resource-docker-image
  public: true
  plan:
  - get: runtime-ci-stemcell-version-bump-resource
    trigger: true
  - put: stemcell-version-bump-resource-image
    params:
      build: runtime-ci-stemcell-version-bump-resource/ci/resources/stemcell-version-bump
    get_params:
      skip_download: true
