---
resources:
- name: chore-bot-source
  type: git
  icon: github
  source:
    branch: main
    uri: git@github.com:pivotal-cf-experimental/relint-trackerbot.git
    private_key: ((relint_trackerbot_read_deploy_key.private_key))

- name: chore-bot-config-and-manifest
  type: git
  icon: github
  source:
    branch: main
    uri: git@github.com:cloudfoundry/relint-team.git
    private_key: ((runtime_ci_private_read_deploy_key.private_key))
    paths:
    - apps/chore_bot

- name: runtime-ci
  type: git
  icon: github
  source:
    branch: main
    uri: https://github.com/cloudfoundry/runtime-ci

jobs:
- name: deploy-chore-bot
  serial: true
  plan:
  - in_parallel:
    - get: chore-bot-source
    - get: chore-bot-config-and-manifest
      trigger: true
    - get: runtime-ci
  - task: unit-tests
    file: runtime-ci/tasks/run-chore-bot-tests/task.yml
  - task: cf-push
    params:
      CF_DOMAIN: long-lived-sli.cf-for-k8s.relint.rocks
      CF_ORG: team-apps
      CF_USERNAME: ((ll_dep_cf_user))
      CF_PASSWORD: ((ll_dep_cf_admin_pass))
      APP_NAME: chore-bot
    file: runtime-ci/tasks/push-chore-bot/task.yml
