---
resources:
- name: runtime-ci
  type: git
  icon: github-box
  source:
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: cf-deployment-concourse-tasks
  type: git
  icon: github-box
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: relint-envs
  type: git
  icon: github-box
  source:
    branch: main
    uri: git@github.com:cloudfoundry/relint-envs.git
    private_key: ((hagrid_env_readwrite_deploy_key.private_key))

# Time
- name: every-monday-morning
  type: time
  icon: clock-outline
  source:
    start: 0:00
    stop: 0:30
    interval: 24h
    days: [ Monday ]
    location: America/Los_Angeles

jobs:
- name: update-infrastructure-concourse
  serial: true
  public: true
  plan:
  - timeout: 12h
    do:
    - in_parallel:
      - get: relint-envs
      - get: runtime-ci
      - get: cf-deployment-concourse-tasks
      - get: every-monday-morning
        trigger: true
    - task: update-infrastructure
      file: runtime-ci/tasks/bbl-up/task.yml
      params:
        BBL_STATE_DIR: environments/ci/concourse/bbl-state
        BBL_IAAS: gcp
        BBL_ENV_NAME: concourse
        BBL_GCP_SERVICE_ACCOUNT_KEY: environments/ci/concourse/google_account_creds.json
        BBL_GCP_REGION: us-central1
        BBL_LB_TYPE: concourse
      input_mapping:
        bbl-state: relint-envs
        bbl-config: relint-envs
      ensure:
        put: relint-envs
        params:
          repository: updated-bbl-state
          rebase: true
