---
resources:
- name: runtime-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: relint-envs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/relint-envs.git
    private_key: ((hagrid_env_readwrite_deploy_key.private_key))

jobs:
- name: update-infrastructure-concourse
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - timeout: 12h
    do:
    - aggregate:
      - get: relint-envs
      - get: runtime-ci
    - task: update-infrastructure
      file: runtime-ci/bbl-up/task.yml
      params:
        BBL_STATE_DIR: environments/ci/concourse/bbl-state
        BBL_IAAS: gcp
        BBL_ENV_NAME: concourse
        BBL_GCP_SERVICE_ACCOUNT_KEY: environments/ci/concourse/google_account_creds.json
        BBL_GCP_REGION: us-central1
        BBL_LB_TYPE: concourse
      input_mapping:
        bbl-state: relint-envs
        bbl-config: relint-envs
      ensure:
        put: relint-envs
        params:
          repository: updated-bbl-state
          rebase: true
