resources:
- name: runtime-ci
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: cf-deployment
  type: git
  icon: github
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-deployment.git
    paths:
    - ci/*

- name: cf-acceptance-tests
  type: git
  icon: github
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
    paths:
    - ci/*

- name: cf-smoke-tests-release
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests-release.git
    paths:
    - ci/*

- name: uptimer
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/uptimer.git
    paths:
    - ci/*

- name: cf-deployment-concourse-tasks
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/cf-deployment-concourse-tasks.git
    private_key: ((ard_wg_gitbot_ssh_key.private_key))

- name: cf-for-k8s
  type: git
  icon: github
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-for-k8s.git
    paths:
    - ci/*

- name: cf-test-helpers
  type: git
  icon: github
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-test-helpers.git
    paths:
      - ci/*

- name: daily
  type: time
  icon: clock-outline
  source:
    start: 3:00 -0700
    stop: 4:30 -0700
    interval: 24h

jobs:
- name: all-jobs-public
  public: true
  plan:
  - in_parallel:
    - get: runtime-ci
      trigger: true
  - task: validate-all-jobs-public
    file: runtime-ci/tasks/validate-all-jobs-public/task.yml

- name: verify-every-task-is-used-in-a-pipeline
  public: true
  plan:
  - in_parallel:
    - get: runtime-ci
      trigger: true
    - get: cf-deployment
      trigger: true
    - get: cf-acceptance-tests
      trigger: true
    - get: cf-smoke-tests-release
      trigger: true
    - get: uptimer
      trigger: true
    - get: cf-deployment-concourse-tasks
      trigger: true
    - get: cf-for-k8s
      trigger: true
    - get: cf-test-helpers
      trigger: true
  - task: verify-every-task-is-used-in-a-pipeline
    file: runtime-ci/tasks/verify-every-task-is-used-in-a-pipeline/task.yml

- name: stale-job-alert
  public: true
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: runtime-ci
  - task: stale-job-alert
    file: runtime-ci/tasks/stale-job-alert/task.yml

- name: run-update-manifest-releases-unit-tests
  public: true
  plan:
  - in_parallel:
    - get: runtime-ci
      trigger: true
  - task: run-update-manifest-releases-unit-tests
    file: runtime-ci/tasks/run-update-manifest-releases-unit-tests/task.yml
