resources:
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: cf-deployment
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-deployment.git
    paths:
    - ci/*

- name: cf-acceptance-tests
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
    paths:
    - ci/*

- name: cf-smoke-tests-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-smoke-tests-release.git
    paths:
    - ci/*

- name: relint-acceptance-env
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/relint-acceptance-env.git
    private_key: ((relint_acceptance_deploy_key.private_key))
    paths:
    - ci/*

- name: daily
  type: time
  source:
    start: 3:00 -0700
    stop: 4:30 -0700
    interval: 24h

jobs:
- name: all-jobs-public
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
      trigger: true
  - task: validate-all-jobs-public
    file: runtime-ci/tasks/validate-all-jobs-public/task.yml

- name: verify-every-task-is-used-in-a-pipeline
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
      trigger: true
    - get: cf-deployment
      trigger: true
    - get: cf-acceptance-tests
      trigger: true
    - get: cf-smoke-tests-release
      trigger: true
    - get: relint-acceptance-env
      trigger: true
  - task: verify-every-task-is-used-in-a-pipeline
    file: runtime-ci/tasks/verify-every-task-is-used-in-a-pipeline/task.yml

- name: stale-job-alert
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: daily
      trigger: true
    - get: runtime-ci
  - task: stale-job-alert
    file: runtime-ci/tasks/stale-job-alert/task.yml

- name: run-update-manifest-releases-unit-tests
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
      trigger: true
  - task: run-update-manifest-releases-unit-tests
    file: runtime-ci/tasks/run-update-manifest-releases-unit-tests/task.yml
