---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: latest

inputs:
- name: cf-deployment
- name: runtime-ci
- name: stemcell

outputs:
- name: updated-cf-deployment

run:
  path: runtime-ci/tasks/update-base-manifest-stemcell/task
