#!/bin/bash

set -eu

root_dir="${PWD}"
cf_target="api.${SYSTEM_DOMAIN}"
CF_PASSWORD=$(bosh interpolate env-repo/${VARS_STORE_PATH} --path=/uaa_scim_users_admin_password)

echo "Setting target to ${cf_target}"
cf api --skip-ssl-validation "${cf_target}"

echo "Authenticating as admin"
cf auth admin "${CF_PASSWORD}"

echo "Listing existing feature flags"
cf feature-flags

echo "Enabling diego feature flag"
cf enable-feature-flag diego_docker || true
