#!/bin/bash

# This concourse task results in:
# 1. Bosh create-env manifest complete with ca-certs, credentials, etc.
set -xeu

root_dir=$PWD

pushd ${root_dir}/env-repo
  bosh -n delete-env ${root_dir}/cf-gcp-infrastructure/deployments/bosh.yml

  if [[ -n $(git status --porcelain) ]]; then
    git config user.name "CF MEGA BOT"
    git config user.email "cf-mega@pivotal.io"
    git add .
    git commit -m "Commit bosh state file"
  fi
popd

shopt -s dotglob
cp -R env-repo/* updated-env-repo/
