#!/bin/bash

set -xeu

root_dir=$PWD

export DEPLOYMENT_VAR_FILE=${root_dir}/env-repo/infrastructure/bosh/deployment-vars.yml

pushd ${root_dir}/env-repo
  # Bosh create-env places the state file in the same directory as the manifest. Since we want the state file
  # in the env-repo, we copy the manifest template to our env-repo so we can commit it.
  cp ${root_dir}/cf-gcp-infrastructure/deployments/bosh.yml infrastructure/bosh/bosh.yml
  bosh -n interpolate -l ${DEPLOYMENT_VAR_FILE} --var-errs infrastructure/bosh/bosh.yml > /dev/null
  bosh -n delete-env --var-file=${DEPLOYMENT_VAR_FILE} infrastructure/bosh/bosh.yml

  if [[ -n $(git status --porcelain) ]]; then
    git config user.name "CF MEGA BOT"
    git config user.email "cf-mega@pivotal.io"
    git add .
    git commit -m "Commit bosh state file"
  fi
popd

shopt -s dotglob
cp -R env-repo/* updated-env-repo/
