---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 3.1-slim

inputs:
- name: runtime-ci

run:
  path: runtime-ci/tasks/validate-all-jobs-public/task.rb

params:
  RUNTIME_CI_DIR: runtime-ci/ci
