#!/bin/bash

set -u

EXCEPTION_TASKS=("scripts/ci/create-final-release-bucket/task.yml" "scripts/ci/run-errand-bbl-bosh-2-0/task.yml")

pushd runtime-ci >> /dev/null
  FAIL=false
  for task_file in scripts/ci/*/task.yml; do
    is_exception=false
    for exception_candidate in ${EXCEPTION_TASKS[*]}; do
      if [[ "$exception_candidate" == "$task_file" ]]; then
        is_exception=true
      fi
    done
    if [[ ! $is_exception ]]; then
      ack "$task_file" pipelines >> /dev/null
    fi
    # task_is_used "$task_file"
    EXIT_STATUS=$?
    if [[ $EXIT_STATUS -ne 0 ]]; then
      FAIL=true
      echo "$task_file is not used in any pipeline"
    fi
  done

  if $FAIL; then
    exit 1
  fi
