#!/bin/bash

set -u

declare -A EXCEPTION_TASKS
EXCEPTION_TASKS["scripts/ci/create-final-release-bucket/task.yml"]=1
EXCEPTION_TASKS["scripts/ci/run-errand-bbl-bosh-2-0/task.yml"]=1

pushd runtime-ci >> /dev/null
  FAIL=false
  for task_file in scripts/ci/*/task.yml; do
    if [[ ${EXCEPTION_TASKS["$task_file"]} -ne 1 ]]; then
      ack "$task_file" pipelines >> /dev/null
    fi
    # task_is_used "$task_file"
    EXIT_STATUS=$?
    if [[ $EXIT_STATUS -ne 0 ]]; then
      FAIL=true
      echo "$task_file is not used in any pipeline"
    fi
  done

  if $FAIL; then
    exit 1
  fi
