#!/bin/bash
set -xeu

cp -R cf-acceptance-tests /go/src/github.com/cloudfoundry/

cd /go/src/github.com/cloudfoundry/cf-acceptance-tests
go get github.com/onsi/ginkgo/ginkgo

set +e
run-cats

exit $?
