#!/bin/bash
set -ex

# Cannot set -u before sourcing .bashrc because of all
# the unbound variables in things beyond our control.
source ~/.bashrc

set -u

cd cf-canaries

# install the canaries application name
bundle
gem build cf_canaries.gemspec
gem install cf_canaries-0.1.3.gem

SKIP_SSL_VALIDATION=${SKIP_SSL_VALIDATION:?"SKIP_SSL_VALIDATION must be provided"}
CF_API_ENDPOINT=${CF_API_ENDPOINT:?"CF_API_ENDPOINT must be provided"}
CF_API_ADMIN_USER=${CF_API_ADMIN_USER:?"CF_API_ADMIN_USER must be provided"}
CF_API_CANARY_USER=${CF_API_CANARY_USER:?"CF_API_CANARY_USER must be provided"}
CANARY_ORG=${CANARY_ORG:?"CANARY_ORG must be provided"}
CANARY_SPACE=${CANARY_SPACE:?"CANARY_SPACE must be provided"}
NUM_ZERO_DOWNTIME_APPS=${NUM_ZERO_DOWNTIME_APPS:?"NUM_ZERO_DOWNTIME_APPS must be provided"}
NUM_INSTANCES_PER_APP=${NUM_INSTANCES_PER_APP:?"NUM_INSTANCES_PER_APP must be provided"}
NUM_INSTANCES_CANARY_INSTANCES=${NUM_INSTANCES_CANARY_INSTANCES:?"NUM_INSTANCES_CANARY_INSTANCES must be provided"}

set +x
CF_API_ADMIN_PASSWORD=${CF_API_ADMIN_PASSWORD:?"CF_API_ADMIN_PASSWORD must be provided"}
CF_API_CANARY_PASSWORD=${CF_API_CANARY_PASSWORD:?"CF_API_CANARY_PASSWORD must be provided"}
set -x

SKIP_SSL_VALIDATION_FLAG=
if [ "$SKIP_SSL_VALIDATION" == true ]; then
         SKIP_SSL_VALIDATION_FLAG="--skip-ssl-validation"
fi

cf api "$CF_API_ENDPOINT" $SKIP_SSL_VALIDATION_FLAG
set +x
echo "Authenticating as $CF_API_ADMIN_USER"
cf auth "$CF_API_ADMIN_USER" "$CF_API_ADMIN_PASSWORD"
echo "Succeeded authenticating"
echo "Creating canary user $CF_API_CANARY_USER"
cf create-user "$CF_API_CANARY_USER" "$CF_API_CANARY_PASSWORD"
echo "Succeeded creating user"
set -x

set +e
cf create-org "$CANARY_ORG"
cf target -o "$CANARY_ORG"
cf create-space "$CANARY_SPACE"
cf target -s "$CANARY_SPACE"
cf set-space-role "$CF_API_CANARY_USER" "$CANARY_ORG" "$CANARY_SPACE" SpaceDeveloper
set -e

set +x
echo "Running command:
canaries --number-of-zero-downtime-apps=$NUM_ZERO_DOWNTIME_APPS \\
         --number-of-instances-canary-instances=$NUM_INSTANCES_CANARY_INSTANCES \\
         --number-of-instances-per-app=$NUM_INSTANCES_PER_APP \\
         --target=$CF_API_ENDPOINT \\
         --app-domain=$CF_APPS_DOMAIN \\
         --username=$CF_API_CANARY_USER \\
         --password=\$CF_API_CANARY_PASSWORD \\
         --organization=$CANARY_ORG \\
         --space=$CANARY_SPACE \\
         $SKIP_SSL_VALIDATION_FLAG"
canaries --number-of-zero-downtime-apps="$NUM_ZERO_DOWNTIME_APPS" \
         --number-of-instances-canary-instances="$NUM_INSTANCES_CANARY_INSTANCES" \
         --number-of-instances-per-app="$NUM_INSTANCES_PER_APP" \
         --target="$CF_API_ENDPOINT" \
         --app-domain="$CF_APPS_DOMAIN" \
         --username="$CF_API_CANARY_USER" \
         --password="$CF_API_CANARY_PASSWORD" \
         --organization="$CANARY_ORG" \
         --space="$CANARY_SPACE" \
         $SKIP_SSL_VALIDATION_FLAG
echo "Succeeded running command"
set -x
