#!/bin/bash -exu

function check_input_params() {
  if [ -z "$DEPLOYMENT_NAME" ]; then
    echo "DEPLOYMENT_NAME has not been set"
    exit 1
  fi
  if [ -z "$ERRAND_NAME" ]; then
    echo "ERRAND_NAME has not been set"
    exit 1
  fi
}

function setup_bosh_env_vars() {
  set +x
  pushd bbl-state
    BOSH_CA_CERT="$(bbl director-ca-cert)"
    export BOSH_CA_CERT
    BOSH_ENVIRONMENT=$(bbl director-address)
    export BOSH_ENVIRONMENT
    BOSH_CLIENT=$(bbl director-username)
    export BOSH_CLIENT
    BOSH_CLIENT_SECRET=$(bbl director-password)
    export BOSH_CLIENT_SECRET
  popd
  set -x
}

function main() {
  check_input_params
  setup_bosh_env_vars

  bosh -d "${DEPLOYMENT_NAME}" run-errand "${ERRAND_NAME}"
}

main
