#!/bin/bash -exu

function setup_bosh_env_vars() {
  set +x
  pushd bbl-state
    BOSH_CA_CERT="$(bbl director-ca-cert)"
    export BOSH_CA_CERT
    BOSH_ENVIRONMENT=$(bbl director-address)
    export BOSH_ENVIRONMENT
    BOSH_CLIENT=$(bbl director-username)
    export BOSH_CLIENT
    BOSH_CLIENT_SECRET=$(bbl director-password)
    export BOSH_CLIENT_SECRET
  popd
  set -x
}

function main() {
  setup_bosh_env_vars

  bosh \
    -n \
    -d "${DEPLOYMENT_NAME}" \
    run-errand "${ERRAND_NAME}" \
    --keep-alive
}

main
