#!/bin/bash

# TODO: send `key` to task.yml, add it to existing pipeline,
# make sure we didn't break anything, then add a new task to the pipeline to stick the bbl version in there.
# NB: we probably need to figure out how to pass SHAs to this thing as well

if [ -e input-version-json/version.json ]; then
  cat input-version-json/version.json | jq '. + {"'$key'": "'$(cat version/version)'"}' > version-json/version.json
else
  echo '{"'$key'": "'$(cat version/version)'"}' | jq . > version-json/version.json
fi
