---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/relint-base

inputs:
- name: runtime-ci
- name: version
- name: input-version-json

outputs:
- name: version-json

run:
  path: runtime-ci/tasks/create-version-json/task

params:
  key: version
