---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/relint-base

inputs:
- name: runtime-ci
- name: cf-deployment
- name: cf-acceptance-tests
- name: cf-smoke-tests-release
- name: uptimer
- name: cf-deployment-concourse-tasks
- name: cf-for-k8s

run:
  path: runtime-ci/tasks/verify-every-task-is-used-in-a-pipeline/task
