#!/bin/bash

set -u

main() {
  local PIPELINE_REPOS=(runtime-ci cf-deployment cf-acceptance-tests cf-smoke-tests-release uptimer cf-deployment-concourse-tasks cf-cli-v7-cats)

  pushd runtime-ci >> /dev/null
    FAIL=false
    for task_file in tasks/*/task.yml; do
      FOUND_IN_REPO=false
      for repo in ${PIPELINE_REPOS[@]}; do
        ack "$task_file" ../$repo/ci >> /dev/null
        if [[ $? -eq 0 ]]; then
          FOUND_IN_REPO=true
          break
        fi
      done

      if [[ $FOUND_IN_REPO == "false" ]]; then
        FAIL=true
        echo "$task_file is not used in any pipeline"
      fi
    done

    if $FAIL; then
      exit 1
    fi
  popd >> /dev/null

}

main "$@"
