#!/bin/bash
set -ex

path="${PATH_TO_VERIFY:-$(pwd)}"

ruby runtime-ci/tasks/check-certs/check-certs.rb \
  --days-left="${DAYS_LEFT_THRESHOLD:-16}" \
  --path="$path" \
  --ignore-paths "$PATHS_TO_IGNORE"
