#!/bin/bash

set -xeu

pushd env-repo
  bbl \
    --state-dir bbl-infrastructure \
    destroy \
    --no-confirm

  if [[ -n $(git status --porcelain) ]]; then
    git config user.name "CF MEGA BOT"
    git config user.email "cf-mega@pivotal.io"
    git add bbl-infrastructure
    git commit -m "Update bbl artifacts"
  fi
popd

shopt -s dotglob
cp -R env-repo/* updated-env-repo/
