#!/bin/bash

set -xeu

if [[ ! -e env-repo/bbl-state.json ]]; then
  echo "no bbl-state.json present -- the infrastructure has already been deleted"
else
  pushd env-repo
    bbl \
      destroy \
      --no-confirm

    if [[ -n $(git status --porcelain) ]]; then
      git config user.name "CF MEGA BOT"
      git config user.email "cf-mega@pivotal.io"
      git add bbl-state.json
      git commit -m "Destroy infrastructure and remove bbl artifacts"
    fi
  popd
fi

shopt -s dotglob
cp -R env-repo/* updated-env-repo/
