#!/bin/bash

set -xeu

pushd env-repo
  pushd bbl-infrastructure
    bbl \
      destroy \
      --no-confirm
  popd

  if [[ -n $(git status --porcelain) ]]; then
    git config user.name "CF MEGA BOT"
    git config user.email "cf-mega@pivotal.io"
    git add bbl-infrastructure
    git commit -m "Update bbl artifacts"
  fi
popd

shopt -s dotglob
cp -R env-repo/* updated-env-repo/
