#!/bin/bash
set -exu

# Inputs
ENDPOINT="${ENDPOINT:?"\$ENDPOINT not set"}"

function main() {
  for i in $(seq 1 $TIMEOUT); do
    set +e
    local rc
    curl --fail "${ENDPOINT}"
    rc="${?}"
    if [ "${rc}" -eq "0" ]; then
      exit 0
    fi
    set -e
    sleep 1
  done

  echo "timeout exceeded"
  exit 1
}

main
