#!/bin/bash -eu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/shared-functions

function main() {
  local root_dir
  root_dir="${1}"

  git clone cf-deployment updated-cf-deployment

 // get releases tarballs ls ${root_dir}/compiled-releases
 // prepend https://storage.googleapis.com/cf-deployment-compiled-releases/
 // take the link + tarballs ---> replace in used-compiled opsfile
 // replace stemcells on all in opsfile

  pushd "runtime-ci/tasks/update-stemcell"
    go run main.go \
      --stemcell-dir="${root_dir}/stemcell" \
      --compiled-releases-dir="${root_dir}/compiled-releases" \
      --cf-deployment-dir="${root_dir}/updated-cf-deployment" \
      --commit-message-path="${root_dir}/commit-message.txt"
  popd

  commit_with_message updated-cf-deployment commit-message.txt
}

main "${PWD}"
