#!/bin/bash -eu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/shared-functions

function main() {
  local root_dir
  root_dir="${1}"

  git clone cf-deployment updated-cf-deployment

  # Bump the stemcell in the main manifest.
  # This is first so that it generates the commit message we use.
  pushd "${root_dir}/runtime-ci/util/update-manifest-releases"
    go run main.go \
      --build-dir "${root_dir}" \
      --input-dir "cf-deployment" \
      --output-dir "updated-cf-deployment" \
      --target "stemcell"
  popd

  # Bump all the compiled releases.
  # This will bump all releases based on directories matching "*-release".
  pushd "${root_dir}/runtime-ci/util/update-manifest-releases"
    go run main.go \
      --build-dir "${root_dir}" \
      --input-dir "cf-deployment" \
      --output-dir "updated-cf-deployment" \
      --target "compiledReleasesOpsfile"
  popd

  commit_with_message "${root_dir}/updated-cf-deployment" "${root_dir}/${COMMIT_MESSAGE_PATH}"
}

main "${PWD}"
