#!/bin/bash
set -exu

aws ec2 describe-instances --filters "Name=tag:Name,Values=${BOSH_LITE_NAME}" \
  --output text --query 'Reservations[*].Instances[*].InstanceId' | \
  tr '\n' ' ' > instances-to-delete

if [ -s instances-to-delete ]
then
  echo "Deleting instances:"
  cat instances-to-delete

  aws ec2 terminate-instances --instance-ids $(cat instances-to-delete)
  aws ec2 wait instance-terminated --instance-ids $(cat instances-to-delete)
else
  echo "No instances to delete"
fi
