---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/relint-base

inputs:
- name: runtime-ci
- name: cf-test-helpers
  path: go/src/github.com/cloudfoundry-incubator/cf-test-helpers
- name: repository

outputs:
- name: updated-repository

run:
  path: runtime-ci/tasks/bump-cf-test-helpers/task

params:
  USE_GO_MOD: true
  REPOSITORY: ""
