#!/bin/bash -exu

source runtime-ci/tasks/shared-functions

export GOPATH="$GOPATH:$PWD/go"

pushd go/src/github.com/cloudfoundry/cf-acceptance-tests
  gvt update github.com/cloudfoundry-incubator/cf-test-helpers

  git add ./vendor
  commit_with_message $PWD <(echo "Update cf-test-helpers dependency")
popd
