#!/bin/bash
set -eu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function setup_bosh_ssh_key() {
  set +x
  chmod 0600 ${bosh_ssh_key}
  pushd "env-repo/${BBL_STATE_DIR}" > /dev/null
    bbl director-ssh-key > ${bosh_ssh_key}
  popd > /dev/null
}

function get_bosh_gateway_host() {
  set +x
  local director_ip_address
  pushd "env-repo/${BBL_STATE_DIR}" > /dev/null
    director_ip_address=$(bbl director-address)
    director_ip_address=${director_ip_address%:25555}
    director_ip_address=${director_ip_address#https://}
  popd > /dev/null
  echo -n ${director_ip_address}
}

function execute_sql() {
  local cmd
  cmd=${1}
  set +x
  &> ssh_output.txt \
    ssh \
    -i ${bosh_ssh_key} \
    -o ProxyCommand='nc -x localhost:`echo $BOSH_ALL_PROXY| cut -f3 -d':'` %h %p' \
    -o "StrictHostKeyChecking=no" \
    ${BOSH_GW_USER}@$(get_bosh_gateway_host) \
    "/var/vcap/packages/mysql/bin/mysql -h ${DB_HOST} -u ${DB_USER} --password=${DB_PASSWORD} -e '${cmd}'"
}

function main() {
  export bosh_ssh_key=$(mktemp)
  setup_bosh_ssh_key ${bosh_ssh_key}
  setup_bosh_env_vars
  set +x

  execute_sql "DROP DATABASE ${DB_NAME}"
  execute_sql "CREATE DATABASE ${DB_NAME}"
}

trap close_bbl_ssh_connection EXIT

main
