#!/bin/bash

set -eu

mkdir -p bbl-state/${BBL_STATE_DIR}

set +x
cat <<JSON > bbl-state/${BBL_STATE_DIR}/bbl-state.json
{
  "bosh": {
    "directorUsername": "${DIRECTOR_USERNAME}",
    "directorPassword": "${DIRECTOR_PASSWORD}",
    "directorSSLCA": "${DIRECTOR_CA_CERT}",
    "directorAddress": "${DIRECTOR_ADDRESS}"
  }
}
JSON
