#!/bin/bash

cp env-repo/infrastructure/bosh/username username/username
cp env-repo/infrastructure/bosh/password password/password
cp env-repo/infrastructure/bosh/bosh-target target/target
cp env-repo/infrastructure/bosh/certs/rootCA.pem ca-cert/ca-cert
