#!/bin/bash

cp env-repo/infrastructure/bosh-init/username username/username
cp env-repo/infrastructure/bosh-init/password password/password
cp env-repo/infrastructure/bosh-init/target target/target
cp env-repo/infrastructure/bosh-init/certs/rootCA.pem ca-cert/ca-cert
