#!/bin/bash

set -exu

git clone cf-deployment-release-candidate cf-deployment-rc-with-updated-version

new_version="v$(cat cf-deployment-version/version)"

pushd cf-deployment-rc-with-updated-version
  old_version="$(bosh int cf-deployment.yml --path /manifest_version)"

  sed -i "s/manifest_version: ${old_version}/manifest_version: ${new_version}/g" cf-deployment.yml

  git add cf-deployment.yml
  git config user.name "ARD WG Bot"
  git config user.email "app-deployments@cloudfoundry.org"
  git commit -m "Update cf-deployment manifest version to ${new_version}"
popd
