---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-cli

inputs:
- name: runtime-ci
- name: cf-deployment-release-candidate
- name: cf-deployment-version

outputs:
- name: cf-deployment-rc-with-updated-version

run:
  path: runtime-ci/tasks/record-cfd-version-in-manifest/task
