#!/bin/bash

set -x
set -e
set -u

DIRECTOR_URL=$(bbl --state-dir env-repo/bbl-infrastructure director-address)
DIRECTOR_UUID=$(bosh -t $DIRECTOR_URL status --uuid)

cat <<EOF > manifest/nats.yml
---
name: nats_1-0
director_uuid: $DIRECTOR_UUID
releases:
- name: nats
  version: latest
resource_pools:
  - name: medium_z2
    cloud_properties:
      instance_type: c3.large
      ephemeral_disk:
        size: 200_536
        type: gp2
      availability_zone: us-east-1d
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
  - name: medium_z1
    cloud_properties:
      instance_type: c3.large
      ephemeral_disk:
        size: 200_536
        type: gp2
      availability_zone: us-east-1a
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
  - name: small_errand
    cloud_properties:
      instance_type: m3.medium
      ephemeral_disk:
        size: 10_240
        type: gp2
      availability_zone: us-east-1a
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
compilation:
  cloud_properties:
    name: random
  network: cf1
  reuse_compilation_vms: true
  workers: 1
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

networks:
  - name: cf1
    subnets:
      - range: 10.0.16.0/20
        reserved:
          - 10.0.16.0 - 10.0.16.3
          - 10.0.16.4 - 10.0.16.24  # dynamic ips for nats
          - 10.0.17.0 - 10.0.31.189
          - 10.0.31.241 - 10.0.31.241 # static ips used by nats bosh 2.0 deployment
          - 10.0.31.244 - 10.0.31.255 # static ips for nats z1
        static:
          - 10.0.31.242 - 10.0.31.243
        gateway: 10.0.16.1
        dns:
          - 10.0.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
        cloud_properties:
          security_groups:
            - sg-172afa6d
          subnet: subnet-cb9c9693
  - name: cf2
    subnets:
      - range: 10.0.48.0/20
        reserved:
          - 10.0.48.0 - 10.0.48.3
          - 10.0.48.4 - 10.0.48.24  # dynamic ips for nats
          - 10.0.49.0 - 10.0.63.189
          - 10.0.63.241 - 10.0.63.241 # static ips used by nats bosh 2.0 deployment
          - 10.0.63.243 - 10.0.63.255 # static ips for nats z2
        static:
          - 10.0.63.242
        gateway: 10.0.48.1
        dns:
          - 10.0.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
        cloud_properties:
          security_groups:
            - sg-172afa6d
          subnet: subnet-ae4a8fe7

jobs:
  - name: nats_z1
    instances: 1
    networks:
    - name: cf1
      static_ips:
      - 10.0.31.242
    resource_pool: medium_z1
    templates:
    - name: nats
      release: nats
    - name: nats_stream_forwarder
      release: nats
    update: {}

  - name: nats_z2
    instances: 1
    networks:
    - name: cf2
      static_ips:
      - 10.0.63.242
    resource_pool: medium_z2
    templates:
    - name: nats
      release: nats
    - name: nats_stream_forwarder
      release: nats
    update: {}

  - name: smoke-tests
    templates:
    - name: smoke-tests
      release: nats
    instances: 1
    resource_pool: small_errand
    lifecycle: errand
    networks:
    - name: cf1
      static_ips:
      - 10.0.31.243

properties:
  nats:
    port: 6363
    user: nats
    password: nats
    machines:
    - 10.0.31.242
    - 10.0.63.242
EOF
