#!/bin/bash
set -xeu

SKIP_SSL_VALIDATION=${SKIP_SSL_VALIDATION:?"SKIP_SSL_VALIDATION must be provided"}
CF_API_ENDPOINT=${CF_API_ENDPOINT:?"CF_API_ENDPOINT must be provided"}
CF_API_ADMIN_USER=${CF_API_ADMIN_USER:?"CF_API_ADMIN_USER must be provided"}
CF_API_CANARY_USER=${CF_API_CANARY_USER:?"CF_API_CANARY_USER must be provided"}
DEPLOYMENT_NAME=${DEPLOYMENT_NAME:?"DEPLOYMENT_NAME must be provided"}
CANARY_ORG=${CANARY_ORG:?"CANARY_ORG must be provided"}
CANARY_SPACE=${CANARY_SPACE:?"CANARY_SPACE must be provided"}

set +x
DATADOG_API_KEY=${DATADOG_API_KEY:?"DATADOG_API_KEY must be provided"}
CF_API_ADMIN_PASSWORD=${CF_API_ADMIN_PASSWORD:?"CF_API_ADMIN_PASSWORD must be provided"}
CF_API_CANARY_PASSWORD=${CF_API_CANARY_PASSWORD:?"CF_API_CANARY_PASSWORD must be provided"}
set -x

SKIP_SSL_VALIDATION_FLAG=
if [ "$SKIP_SSL_VALIDATION" == true ]; then
         SKIP_SSL_VALIDATION_FLAG="--skip-ssl-validation"
fi

cf api "$CF_API_ENDPOINT" $SKIP_SSL_VALIDATION_FLAG

set +x
  echo "Authenticating as $CF_API_ADMIN_USER"
  cf auth "$CF_API_ADMIN_USER" "$CF_API_ADMIN_PASSWORD"
  echo "Succeeded authenticating"
set -x

set +e
  set +x
    echo "Creating canary user $CF_API_CANARY_USER"
    cf create-user "$CF_API_CANARY_USER" "$CF_API_CANARY_PASSWORD"
    echo "Succeeded creating user"
  set -x

  cf create-org "$CANARY_ORG"
  cf create-space "$CANARY_SPACE" -o "$CANARY_ORG"
  cf set-space-role "$CF_API_CANARY_USER" "$CANARY_ORG" "$CANARY_SPACE" SpaceDeveloper
set -e

set +x
  echo "Authenticating as $CF_API_CANARY_USER"
  cf auth "$CF_API_CANARY_USER" "$CF_API_CANARY_PASSWORD"
set -x

cf target -o "$CANARY_ORG" -s "$CANARY_SPACE"

app_name=${APP_NAME:-diego-canary-app}
instance_count=${INSTANCE_COUNT:-20}

pushd diego-release/src/github.com/cloudfoundry-incubator/diegocanaryapp
  cf push "$app_name" --no-start -m 32M -k 64M -b go_buildpack
  app_guid=$(cf app "${app_name}" --guid | tr -d '\n')

  cf curl "/v2/apps/${app_guid}" -X PUT -d '{"diego": true}' > /dev/null

  echo "cf set-env $app_name DATADOG_API_KEY \$DATADOG_API_KEY"
  set +x
  cf set-env "$app_name" DATADOG_API_KEY "${DATADOG_API_KEY}" > /dev/null
  set -x

  cf set-env "$app_name" DEPLOYMENT_NAME "${DEPLOYMENT_NAME}"
  cf start "$app_name"
  cf scale "$app_name" -i "$instance_count"
popd

