---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-cli

inputs:
# runtime-ci git repo (https://github.com/cloudfoundry/runtime-ci.git).
# - This file is located there.
# - The linked task script is located there.
- name: runtime-ci

# cf CLI GitHub release (https://github.com/cloudfoundry/cli/releases).
# - Need a cf CLI release for Windows in order to upload it as a blob.
- name: cf-cli-release

# The BOSH release that needs to have the latest cf CLI release for Windows
# uploaded as a blob.
# - Expected to be a git repo so that the changes can be committed.
# - Any blobs that match this pattern will be removed if they're not a version
#   that is greater than, or equal to, the provided cf CLI release for Windows:
#   `cf8-cli_*_winx64.zip`.
- name: release-repo

outputs:
# The `release-repo` input with the changes applied by the task.
# - Only one blob will match the following pattern: `cf8-cli_*_winx64.zip`.
# - That blob will be the latest release between any already uploaded and the release provided.
# - All changes, if any, will be committed. This output should be pushed as a task later.
- name: updated-release-repo

run:
  path: runtime-ci/tasks/bump-cf-cli-windows-blob/task

params:
  # A yaml file containing the credentials necessary for uploading blobs.
  PRIVATE_YML:
