#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function bosh_update_runtime_config {
  local arguments=""

  for vf in ${VARS_FILES}
  do
    arguments="${arguments} -l vars-files/${vf}"
  done

  bosh \
    -n \
    update-runtime-config \
    runtime-configs/"${RUNTIME_CONFIG_FILE}" \
    ${arguments}
}

function main() {
  setup_bosh_env_vars

  bosh_update_runtime_config
}

main
