#!/bin/bash
set -eu

source cf-deployment-concourse-tasks/shared-functions

if [ -z "${VARS_STORE_PATH}" ]; then
  setup_bosh_env_vars
  CF_PASSWORD=$(get_password_from_credhub cf_admin_password)
else
  CF_PASSWORD=$(bosh interpolate vars-store/${VARS_STORE_PATH} --path=/cf_admin_password)
fi

echo "Setting target to api.${SYSTEM_DOMAIN}"
cf api --skip-ssl-validation api.${SYSTEM_DOMAIN}

echo "Authenticating as admin"
cf auth admin "${CF_PASSWORD}"

echo "Creating service discovery domain"
cf curl /v2/shared_domains -d '{
 "name": "apps.internal",
 "internal": true
}'
