#!/bin/bash -exu

# Not able to resolve our import via shellcheck, so disable warning
# shellcheck disable=SC1091
source runtime-ci/tasks/shared-functions

function main() {
  local root_dir
  root_dir="${1}"

  git clone cf-deployment updated-cf-deployment

  pushd "${root_dir}/runtime-ci/util/update-manifest-releases"
    go run main.go \
      --build-dir "${root_dir}" \
      --input-dir "cf-deployment" \
      --output-dir "updated-cf-deployment"
  popd

  commit_with_message "${root_dir}/updated-cf-deployment" "${root_dir}/${COMMIT_MESSAGE_PATH}"
}

main "${PWD}"
