#!/bin/bash

set -exu

# Date
current_date=$(date -u "+%Y-%m-%dT%H:%M:%SZ")

cf_release_sha=$(cd cf-release; git rev-parse HEAD)
diego_release_sha=$(cd diego-release-master; git rev-parse HEAD)
bosh_lite_sha=$(cd bosh-lite; git rev-parse HEAD)
cf_sha_diego_sha="${cf_release_sha}-${diego_release_sha}"
function readEndorsement() {
  endorsement=$1
  endorsement_type=$2
  cat diego-cf-compatibility/endorsements/cats/${cf_sha_diego_sha}/${endorsement}.json | jq --raw-output ".[\"${endorsement_type}\"]"
}

tar xzf aws-stemcell/stemcell.tgz
aws_stemcell_name=$(grep -e "^name" stemcell.MF | cut -f2 -d' ')
aws_stemcell_version=$(grep -e "^version" stemcell.MF | cut -f2 -d' ' | tr -d "'")
aws_stemcell="${aws_stemcell_name}/${aws_stemcell_version}"
aws_director_version=$(readEndorsement aws director-version)
aws_build_url=$(readEndorsement aws build-url)

tar xzf bosh-lite-stemcell/stemcell.tgz
bosh_lite_stemcell_name=$(grep -e "^name" stemcell.MF | cut -f2 -d' ')
bosh_lite_stemcell_version=$(grep -e "^version" stemcell.MF | cut -f2 -d' ' | tr -d "'")
bosh_lite_stemcell="${bosh_lite_stemcell_name}/${bosh_lite_stemcell_version}"
bosh_lite_director_version=$(readEndorsement bosh-lite director-version)
bosh_lite_build_url=$(readEndorsement bosh-lite build-url)

tar xzf vsphere-stemcell/stemcell.tgz
vsphere_stemcell_name=$(grep -e "^name" stemcell.MF | cut -f2 -d' ')
vsphere_stemcell_version=$(grep -e "^version" stemcell.MF | cut -f2 -d' ' | tr -d "'")
vsphere_stemcell="${vsphere_stemcell_name}/${vsphere_stemcell_version}"
vsphere_director_version=$(readEndorsement vsphere director-version)
vsphere_build_url=$(readEndorsement vsphere build-url)

diego_release_version=$(cd diego-final-releases; cat version)
garden_linux_release_version=$(cd garden-linux-release-tarball; cat version)
etcd_release_version=$(cd etcd-release-tarball; cat version)
cflinuxfs2_release_version=$(cd cflinuxfs2-rootfs-release-tarball; cat version)

new_row="${cf_release_sha},${diego_release_sha},${diego_release_version},${garden_linux_release_version},${etcd_release_version},${cflinuxfs2_release_version},${bosh_lite_sha},${aws_stemcell},${bosh_lite_stemcell},${vsphere_stemcell},${aws_director_version},${bosh_lite_director_version},${vsphere_director_version},${aws_build_url},${bosh_lite_build_url},${vsphere_build_url}"
if grep "$new_row" "diego-cf-compatibility/$COMPATIBILITY_FILE"; then
  echo "No changes to be made".
else
  pushd diego-cf-compatibility > /dev/null
    if [[ ! -e "$COMPATIBILITY_FILE" ]]; then
      echo "date,cf-release-commit-sha,diego-release-commit-sha,diego-release-version,garden-linux-release-version,etcd-release-version,cflinuxfs2-rootfs-release-version,bosh_lite_commit_sha,aws_stemcell,bosh_lite_stemcell,vsphere_stemcell,aws-director-version,bosh-lite-director-version,vsphere-director-version,aws-acceptance-tests-build-url,bosh-acceptance-tests-build-url,vsphere-acceptance-tests-build-url" \
        > "$COMPATIBILITY_FILE"
    fi
    echo "${current_date},${new_row}" >> "$COMPATIBILITY_FILE"

    git config user.email "cf-release-integration@pivotal.io"
    git config user.name "CI (automated)"

    git add "$COMPATIBILITY_FILE"
    git commit -m "Update ${COMPATIBILITY_FILE}"
  popd > /dev/null
fi

shopt -s dotglob
cp -R diego-cf-compatibility/* updated-diego-cf-compatibility
